project:
  title: "00_drafts"
bibliography: references.bib
format:
  pdf:
    sanitize: true
    keep-tex: true
    link-citations: true
    colorlinks: true
    documentclass: report
    classoption: [singlecolumn]
    lof: true
    lot: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    include-in-header:
       - text: |
           \usepackage{cancel}
execute:
  echo: false
  warning: false
  include: false
  eval: false
fontfamily: libertinus
