project:
  title: "00_drafts"
bibliography: references.bib
format:
  pdf:
    sanitize: true
    keep-tex: true
    link-citations: true
    colorlinks: true
    documentclass: scrartcl
    classoption: 
      - singlecolumn
      - 9pt 
    lof: true
    lot: true
    geometry:
      - top=30mm
      - bottom=30mm
      - left=20mm
      - heightrounded
    template-partials:
      - title.tex
    include-in-header:
       - text: |
          \usepackage{cancel}
          \usepackage{xcolor}
          \usepackage[noblocks]{authblk}
          \renewcommand*{\Authsep}{, }
          \renewcommand*{\Authand}{, }
          \renewcommand*{\Authands}{, }
          \renewcommand\Affilfont{\small}
execute:
  echo: false
  warning: false
  include: false
  eval: true
fontfamily: libertinus
csl: camb-a.csl
