project:
  title: "00_drafts"

author:
  - name: Authors TBA
    affiliation: TBA
  - name: Chris G Sibley
    orcid: 0000-0002-4064-8800
    affiliation: University of Auckland,  New Zealand
  - name: Joseph Bulbulia
    orcid: 0000-0002-5861-2056
    affiliation: Victoria University of Wellington, New Zealand
    email: joseph.bulbulia@vuw.ac.nz
bibliography: references.bib
format:
  pdf:
    keep-tex: true
    link-citations: true
    colorlinks: true
    documentclass: report
    classoption: [singlecolumn]
    lof: true
    lot: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
execute:
  echo: false
  warning: false
  include: true
fontfamily: libertinus
