project:
  title: "00_drafts"

bibliography: references.bib
format:
  pdf:
    keep-tex: true
    link-citations: true
    colorlinks: true
    documentclass: report
    classoption: [singlecolumn]
    lof: true
    lot: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
execute:
  echo: false
  warning: false
  include: true
  eval: false
fontfamily: libertinus
