---
title: "scale descriptions"
format: pdf
bibliography: references.bib
editor: visual
---

# TO DO

#### Rumination

"During the last 30 days, how often did.... you have negative thoughts that repeated over and over?"

Ordinal response options for the Kessler-6 are: "None of the time"; "A little of the time"; "Some of the time"; "Most of the time"; "All of the time."

#### Mini-IPIP 6 (waves: 1-3,4-15)

We measured participants personality with the Mini International Personality Item Pool 6 (Mini-IPIP6) [@sibley2011] which consists of six dimensions and each dimensions is measured with four items:

1.  agreeableness,

    i.  I sympathize with others' feelings.

    ii. I am not interested in other people's problems. (r)

    iii. I feel others' emotions.

    iv. I am not really interested in others. (r)

2.  conscientiousness,

    i.  I get chores done right away.

    ii. I like order.

    iii. I make a mess of things. (r)

    iv. I ften forget to put things back in their proper place. (r)

3.  extraversion,

    i.  I am the life of the party.

    ii. I don't talk a lot. (r)

    iii. I keep in the background. (r)

    iv. I talk to a lot of different people at parties.

4.  honesty-humility,

    i.  I feel entitled to more of everything. (r)

    ii. I deserve more things in life. (r)

    iii. I would like to be seen driving around in a very expensive car. (r)

    iv. I would get a lot of pleasure from owning expensive luxury goods. (r)

5.  neuroticism, and

    i.  I have frequent mood swings.

    ii. I am relaxed most of the time. (r)

    iii. I get upset easily.

    iv. I seldom feel blue. (r)

6.  openness to experience

    i.  I have a vivid imagination.

    ii. I have difficulty understanding abstract ideas. (r)

    iii. I do not have a good imagination. (r)

    iv. I am not interested in abstract ideas. (r)

Each dimension was assessed with four items and participants rated the accuracy of each item as it applies to them from 1 (Very Inaccurate) to 7 (Very Accurate). Items marked with (r) are reverse coded.

#### Honesty-Humility-Modesty Facet (waves: 10-14)

Participants indicated the extent to which they agree with the following four statements from @ashton2008, @campbell2004, and @sibley2011 (1 = Strongly Disagree to 7 = Strongly Agree)

```         
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)

ii. I am an ordinary person who is no better than others.

iii. I wouldn't want people to treat me as though I were superior to them.

iv. I think that I am entitled to more respect than the average person is.
```

#### Age (waves: 1-15)

We asked participants' age in an open-ended question ("What is your age?" or "What is your date of birth").

#### Alcohol Frequency (waves: 6-15)

We measured participants' frequency of drinking alcohol using one item adapted from @ministryofhealth2013 . Participants were asked "How often do you have a drink containing alcohol?" (1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 = Don't know).

#### Alcohol Intensity (waves: 6-15)

We measured participants' intensity of drinking alcohol using one item adapted from [@ministryofhealth2013]. Participants were asked "How many drinks containing alcohol do you have on a typical day when drinking alcohol? (number of drinks on a typical day when drinking)"

#### Body Satisfaction (waves: 2-3, 4-15)

We measured body satisfaction with one item from @stronge_facebook_2015: "I am satisfied with the appearance, size and shape of my body", which participants rated from 1 (very inaccurate) to 7 (very accurate).

#### NZ-Born (waves: 1-2,4-15)

We asked participants "Which country were you born in?" or "Where were you born? (please be specific, e.g., which town/city?)" (waves: 6-15).

#### Felt Belongingness (waves: 1-3, 4-15)

We assessed felt belongingness with three items adapted from the Sense of Belonging Instrument [@hagerty1995]: (1) "Know that people in my life accept and value me"; (2) "Feel like an outsider"; (3) "Know that people around me share my attitudes and beliefs". Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very Accurate). The second item was reversely coded.

#### Charity Donation (waves: 1-3, 4-15)

Using one item from @hoverd2010, we asked participants "How much money have you donated to charity in the last year?". To stablise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.

#### Number of Children (waves: 1-3, 4-15)

We measured number of children using one item from @bulbulia2015. We asked participants "How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, or adopted?" or ""How many children have you given birth to, fathered, or adopted. How many children have you given birth to, fathered, and/or parented?" (waves: 12-15).

#### Sense of Community (waves: 6-15)

We measured sense of community with a single item from @sengupta2013: "I feel a sense of community with others in my local neighbourhood." Participants answered on a scale of 1 (strongly disagree) to 7 (strongly agree).

#### Education Attainment (waves: 1, 4-15)

Participants were asked "What is your highest level of qualification?". We coded participans highest finished degree according to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with overseas school quals coded as Level 3, and all other ancillary categories coded as missing) See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

#### Employment (waves: 1-3, 4-11)

We asked participants "Are you currently employed? (This includes self-employed or casual work)". \* note: This question disappeared in the updated NZAVS Technical documents (Data Dictionary).

#### Job Security (waves: 1-3,4-7,9-15)

Participants indicated their feeling of job security by answering "How secure do you feel in your current job?" on a scale from 1 (not secure) to 7 (very secure).

#### Emotional Regulation (waves: 10-13)

We measured participants' levels of emotional regulation using three items adpated from @gratz_multidimensional_2004 and @gross_individual_2003: (1) "When I feel negative emotions, my emotions feel out of control."; (2) "When I feel negative emotions, I suppress or hide my emotions."; (3) "When I feel negative emotions, I change the way I think to help me stay calm.". Participants were asked to indicate the extent to which they agree with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### European (waves: 1-15)

Participants were asked "Which ethnic group do you belong to (NZ census question)?" or "Which ethnic group(s) do you belong to? (Open-ended)" (wave: 3). Europeans were coded as 1, whereas other ethnicities were coded as 0.

#### Ethnicity (waves: 3)

Based on the New Zealand Cencus, we asked participants "Which ethnic group(s) do you belong to?". The responses were: (1) New Zealand European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6) Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE, TOKELAUAN. Please state:. We coded their answers into four groups: Maori, Pacific, Asian, and Euro (except for Time 3, which used an open-ended measure).

#### Gender (waves: 1-15)

We asked participants' gender in an open-ended question: "what is your gender?" or "Are you male or female?" (waves: 1-5). Female was coded as 0, Male was coded as 1, and gender diverse coded as 3 [@fraser_coding_2020]. (or 0.5 = neither female nor male)

#### Gratitude (waves: 10-15)

We assessed the extent to which participants have gratitude, using three items from @mccullough_grateful_2002: (1) "I have much in my life to be thankful for."; (2) "When I look at the world, I don't see much to be grateful for."; (3) "I am grateful to a wide variety of people.". Participants indicated their agreement with these items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was reversely coded.

#### Home Owner (waves: 4)

Using one item from @houkamau_looking_2015, we asked participants "(Māori) Do you own your own home?(either partly or fully owned)" (1 = Yes, 0 = No)

#### Hours of Exercise (waves: 1, 4-15)

We measured hours of exercising using one item from @sibley2011. We asked participants to estimate and report how many hours they spend in exercise/physical activity last week. To stablise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.

#### Hours of Work (waves: 1, 4-15)

We measured hours of Work using one item from @sibley2011. We asked participants to estimate and report how many hours they spend in working in paid employment last week.

#### Body Mass Index (waves: 2-3, 4-15)

Participants were asked "What is your height? (metres)" and "What is your weight? (kg)". Based on participants indication of their height and weight we calculated the BMI by dividing the weight in kilograms by the square of the height in meters.

#### Disability (waves: 5-15)

We assessed disability with a one item indicator adapted from @verbrugge1997, that asks "Do you have a health condition or disability that limits you, and that has lasted for 6+ months?" (1 = Yes, 0 = No).

#### Fatigue (waves: 5-15)

We assessed subjective fatigue by asking participants, "During the last 30 days, how often did ... you feel exhausted?" Responses were collected on an ordinal scale (0 = None of The Time, 1 = A little of The Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

#### Hours of Sleep (waves: 5-15)

Participants were asked "During the past month, on average, how many hours of *actual sleep* did you get per night".

#### Ethnic group impermeability (waves: 9-13)

We assessed ethnic group impermeability using one item from @mummendey_social_1999. Participants were asked to indicate the extent to which they agree with the statement ("The current income gap between New Zealand Europeans and other ethnic groups would be very hard to change."; 1 = Strongly Disagree to 7 = Strongly Agree).

#### Income (waves: 1-3, 4-15)

Participants were asked "Please estimate your total household income (before tax) for the year XXXX". To stablise this indicator, we first took the natural log of the response + 1, and then centred and standardised the log-transformed indicator.

#### Kessler-6 (waves: 2-3,4-15)

We measured psychological distress using the Kessler-6 scale [@kessler2002], which exhibits strong diagnostic concordance for moderate and severe psychological distress in large, cross-cultural samples [@kessler2010; @prochaska2012]. Participants rated during the past 30 days, how often did... (1) "... you feel hopeless"; (2) "... you feel so depressed that nothing could cheer you up"; (3) "... you feel restless or fidgety"; (4)"... you feel that everything was an effort"; (5) "... you feel worthless"; (6) " you feel nervous?" Ordinal response alternatives for the Kessler-6 are: "None of the time"; "A little of the time"; "Some of the time"; "Most of the time"; "All of the time."

#### Life Meaning (waves: 10-15)

We assessed participants' levels of life meaning using two items from @steger_meaning_2006: (1) My life has a clear sense of purpose; (2) I have a good sense of what makes my life meaningful. Participants indicated their agreement with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### Satisfaction with Life (waves: 1-3,4-15)

We measured life satisfaction with two items adapted from the Satisfaction with Life Scale [@diener1985]: "I am satisfied with my life" and "In most ways my life is close to ideal". Participants responded on a scale from 1 (Strongly Disagree) to 7 (Strongly Agree).

#### Lost Job (waves: 10-15)

Participants were asked to indicate whether they lost their job or had the principal earner in their household lose job in the last year (1 = Yes, 0 = No).

#### NZ Deprivation Index (waves: ??)

We used the NZ Deprivation Index to assign each participant a score based on where they live [@atkinson2019]. This score combines data such as income, home ownership, employment, qualifications, family structure, housing, and access to transport and communication for an area into one deprivation score.

#### National Well-being Index (waves: 1-3, 4-15)

We measured participant's sense of national well-being by asking them to "Please rate your level of satisfaction with the following aspects of your life and New Zealand: (1) The economic situation in New Zealand, (2) The social conditions in New Zealand, and (3) Business in New Zealand" on a scale from 0 (Completely Dissatisfied) to 10 (Completely Satisfied) [@tiliouine2006].

#### NZSEI-13 (waves: 8-15)

We assessed occupational prestige and status using the New Zealand Socio-economic Index 13 (NZSEI-13) [@fahy2017]. This index uses the income, age, and education of a reference group, in this case the 2013 New Zealand census, to calculate an score for each occupational group. Scores range from 10 (Lowest) to 90 (Highest). This list of index scores for occupational groups was used to assign each participant a NZSEI-13 score based on their occupation.

#### Parent (waves: 5-15)

Participants were asked "If you are a parent, what is the birth date of your eldest child?" or "If you are a parent, in which year was your eldest child born?" (waves: 10-15). Parents were coded as 1, while the others were coded as 0. .

#### Living with Partner (waves: 4-7, 12)

Participants were asked "Do you live with your partner?" (1 = Yes, 0 = No).

#### Perfectionism (waves: 10-15)

We assessed participants' perfectionism using three items from @rice_short_2014: (1) Doing my best never seems to be enough; (2) My performance rarely measures up to my standards; (3) I am hardly ever satisfied with my performance. Participants indicated the extent to which they agree with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### Political Wing (waves: 3,4-15)

We measured participants' political orientation using a single item adapted from @jost2006 . Participants were asked to rate how politically left-wing versus right-wing they see themselves as being (1 = Extremely Left-wing to 7 = Extremely Right-wing)

#### Powerlessness (waves: 10-13)

Participants' Powerlessness was measured using two items: (1) I do not have enough power or control over important parts of my life; (2) Other people have too much power or control over important parts of my life. Participants indicated their agreement with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### Self-Respect (waves: 3, 4-11, 15)

We assessed participants' levels of self-respect using an item adapted from @tyler_understanding_1996. Participant indicated the extent to which they agree with the statement ("If they knew me, most NZers would respect what I have accomplished in life") on a likert scale (1 = Strongly Disagree to 7 = Strongly Agree)

#### Retired (waves: 10-15)

Participants were asked to indicate whether they were retired or not in the last year (1 = Yes, 0 = No).

#### Rumination (waves: 2-3,4-15)

We used a single item adapted from @nolen-hoeksema_effects_1993 to measure participants' level of rumination. Participants were asked, "During the last 30 days, how often did...you have negative thoughts that repeated over and over?" and indicated their frequency of rumination on an ordinal scale (0 = None of The time, 1 = A little of the time, 2 = some of the time, 3 = most of the time, 4 = all of the time)

#### Self-Control (waves: 5-15)

Participants were asked to indicate the extent to which they endorse the two items ("In general, I have a lot of self-control", "I wish I had more self-discipline") from @tangney_high_2004. The responses to the items ranged from 1 (Strongly Disagree) to 7 (Strongly Agree).

#### Self-Esteem (waves: 1-3, 4-15)

We measured participants' self-esteem using three items adapted from @rosenberg1965. Participants were instructed to circle the number that best represents how accurately each statement describes them. Participants responded to the items ("On the whole am satisfied with myself.", "Take a positive attitude toward myself", "Am inclined to feel that I am a failure") on a likert-type scale (1 = Very inaccurate to 7 = Very accurate).

#### Semiretired (waves: 10-15)

SAME AS RETIRED

#### Sexual Orientation (waves: 5-15)

Participants were asked to report their sexual orientation: "How would you describe your sexual orientation? (e.g., heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)".

#### Sexual Satisfaction (waves: 10-15)

Participants were asked "How satisfied are you with your sex life?" (1 = Not satisfied to 7 = Very satisfied).

#### Health Condition or Disability (waves: 5-15)

Participants' subjective health was measured using one item ("Do you have a health condition or disability that limits you, and that has lasted for 6+ months?"; 1 = Yes, 0 = No) adapted from @verbrugge1997.

#### Smoker (waves: 4-15)

We asked participants whether they are currently smoking or not (1 = Yes or 0 = No), using a single item: "Do you currently smoke?" or "Do you currently smoke tobacco cigarettes?" (waves: 10-15) from @muriwai_looking_2018.

#### Standard Living (waves: 1-3, 4-15)

We measured participants' satisfaction with their standard of living using an item from the Australian Unity Wellbeing Index [@cummins_developing_2003]. Participants read an instruction ("Please rate your level of satisfaction with the following aspects of your life and New Zealand.") and responded to an item ("Your standard of living") on a 10-point scale (0 = completely dissatisfied to 10 = completely satisfied).

#### Social Support (waves: 1-3, 4-15)

Participants' perceived social support was measured using three items from @cutrona1987 and @williams_cyberostracism_2000: (1) "There are people I can depend on to help me if I really need it"; (2) "There is no one I can turn to for guidance in times of stress"; (3) "I know there are people I can turn to when I need help." Participants indicated the extent to which they agree with those items (1 = Strongly Disagree to 7 = Strongly Agree). The second item was negatively-worded, so we reversely recorded the responses to this item.

#### Living in an Urban Area (waves: 1-15)

We coded whether they are living in an urban or rural area (1 = Urban, 0 = Rural) based on the addresses provided.

#### Vengeful Rumination (waves: 10-15)

We assessed participants' vengeful rumination using three items, respectively adapted from @caprara_indicators_1986 and @berry_forgivingness_2005, and developed for NZAVS: (1) Sometimes I can't sleep because of thinking about past wrongs I have suffered; (2) I can usually forgive and forget when someone does me wrong; (3) I find myself regularly thinking about past times that I have been wronged. Participants indicated their agreement with these items (1 = Strongly Disagree to 7 = Strongly Agree). The values for the second item were reversely coded.

#### Volunteers (waves: 1, 4-15)

Participants were asked,"Please estimate how many hours you spent doing each of the following things last week" and responded to an item ("voluntary/charitable work"), from [@sibley2011].

#### Personal Well-being (waves: 1-3, 4-15)

We measured participants' subjective wellbeing using three items from the Australian Unity Wellbeing Index [@cummins_developing_2003]: (1) your health; (2) Your standard of living; (3) your future security; (4) Your personal relationships. Participants read an instruction ("The following items assess your current satisfaction with different aspects of your life and aspects of New Zealand more generally") and indicated their satisfaction with those items (0 = Completely Dissatisfied to 10 = Completely Satisfied).

#### Satisfaction with NZ Environment (waves: 1-3, 4-15)

Using one item Adapted from the International Wellbeing Index [@tiliouine2006], we asked participants to assess their current satisfaction with the quality of New Zealand's natural environment (1 = Completely dissatisfied to 10 = Completely satisfied).

#### Opinions about Government Spending on Motoways (waves: 1, 4-5, 10-11)

Participants indicated the extent to which they oppose or support an item ("Increased government spending on new motorways") from @milfont2022 on a likert scale (1 = Strongly Oppose to 7 = Strongly Support).

#### Opinions about Government Subsidy of Public Transport (waves: 1, 4-5, 10-11)

Participants indicated the extent to which they oppose or support an item ("Government subsidy of public transport") from @milfont2020 on a likert scale (1 = Strongly Oppose to 7 = Strongly Support).

#### Protecting Native Species (waves: 2, 5, 8-9, 11, 14-15)

Participants indicated the extent to which they agree with an item ("Protecting New Zealand's native species should be a national priority"), 1 = Strongly Disagree to 7 = Strongly Agree. (Developed for NZAVS)

#### Climate Change Belief (waves: 1-15)

We measured participants' climate change belief using three items from @sibley2013 and @milfont2022: (1) "Climate change is real"; (2) "Climate change is caused by humans"; (3) "I am deeply concerned about climate change." (waves: 5-15). Participants indicated the extent to which they agree with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### Valuing Environmental Protection (waves: 1-3, 4, 7-8)

Using one item from @schwartz1992, we asked participants to indicate how important protecting the environment (preserving nature) is for them as a guiding principle in your life (-1 = Opposed to my values to 7 = Of supreme importance).

#### Personal Environmental Sacrifice (waves: 1-3, 4-6, 9)

We measured participants' sacrifices for the national environment using four items, adapted from @liu2012: (1) Environmental sacrifices made: "Have you made sacrifices to your standard of living (e.g., accepted higher prices, driven less, conserved energy) in order to protect the environment?"; (2) Willingness to make environmental sacrifices: "Are you willing to make sacrifices to your standard of living (e.g., accept higher prices, drive less, conserve energy) in order to protect the environment?" (3) Daily routine changed: "Have you made changes to your daily routine in order to protect the environment?" (waves: 1-6); (4) Willingness to change daily routine: "Are you willing to change your daily routine in order to protect the environment?" (waves: 1-6). Responses to these items ranged from Definitely No (1) to Definitely Yes (7).

#### Environmental Sacrifice Norm Perception (waves: 1-3, 4-6, 9)

Environmental sacrifice norm perceptions was measured with one single question, adapted from @liu2012: "Do you think most New Zealanders are willing to make sacrifices to their standard of living in order to protect the environment?". Responses to these items ranged from Definitely No (1) to Definitely Yes (7).

#### Opinion about the Government's Carbon Emissions Regulation (waves: )

We asked participants' opinion about the government's carbon emissions regulation using one item from @satherley2020. Participants were asked to indicate their agreement with the statement ("The New Zealand government should be involved in regulating carbon emissions.") on a scale ranging from Strongly Disagree (1) to Strongly Agree (7).

#### Quality of Waterways (waves: 9-11, 14-15)

Participants rated their level of satisfaction with one item ("the quality and health of the waterways in your local region") from @milfont2022 (0 = Completely Dissatisfied to 10 = Completely Satisfied)

#### Valuing Unity with Nature (waves: 7)

Using one item from @schwartz1992, We asked participants to indicate how important UNITY WITH NATURE (fitting into nature) is for them as a guiding principle in your life (-1 = Opposed to my values to 7 = Of supreme importance).

#### Possum Control (waves: 3, 5, 8-9, 11)

Participants were asked, "Do you support the use of 1080 poison for possum control in New Zealand?". Responses to this item ranged from Definitely No (1) to Definitely Yes (7).

#### Pro-Environmental Efficacy (waves: 1-3, 4-6, 8-9, 12-15)

We measured participants' pro-environmental efficacy using two items from @sharma: (1) belief: "By taking personal action I believe I can make a positive difference to environmental problems."; (2) feeling:"I feel I can make a difference to the state of the environment." Participants indicated the extent to which they agree with these items (1 = Strongly Disagree to 7 = Strongly Agree).

#### Earthquake Anxiety (waves: 4-14)

Using one item from @rowney2014, we asked participatns "During the last 30 days, how often did you worry that a big earthquake might hit your region" (0 = None of the time to 4 = All of the time)?

#### Affected by Christchurch Earthquakes (waves: 3, 6)

Participants were asked "Where you personally affected by the Christchurch earthquakes?" (1 = Yes or 0 = No)

#### Belief in God (waves: 2-5, 7-15)

Using one item from @eurobarometer2005, we asked participants "Do you believe in a God" (1 = Yes, 0 = No).

#### Belief in Sprituality (waves: 2-5, 7-15)

Using one item from @eurobarometer2005, we asked participants "Do you believe in some form of spirit or lifeforce? (1 = Yes, 0 = No).

#### Religion Affiliation (waves: 1-15)

Using one item from @hoverd2010, we asked participants to indicate their religion identification ("Do you identify with a religion and/or spiritual group?") on a binary response (1 = Yes, 0 = No). We then asked "What religion or spiritual group?" in a open-ended question. These questions are used in the New Zealand Census.

#### Religious Identification (waves: 1-15)

If participants answered *yes* to "Do you identify with a religion and/or spiritual group? we asked"How important is your religion to how you see yourself?" (1 = Not important, 7 = Very important), using one item from @hoverd2010. Those participants who were not religious were imputed a score of "1".

#### Frequency of Church Attendance (waves: 2-11, 13-15)

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of church attendance using one item from @sibley2012: "how many times did you attend a church or place of worship in the last month?". Those participants who were not religious were imputed a score of "0".

#### Spiritual Identification (waves: 8, 10, 12-15)

Spiritual identification was measured using one item ("I identify as a spiritual person.") from @postmes_single-item_2013. Participants indicated their agreement with this item (1 = Strongly Disagree to 7 = Strongly Agree).

#### Frequency of Prayer (waves: 3-11, 13-15)

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of prayer by asking the question ("how many times did you pray in the last week?") from @bulbulia2015. Those participants who were not religious were imputed a score of "0".

#### Frequency of Scripture Reading (waves: 3.5, 6-11, 13-15)

If participants answered *yes* to "Do you identify with a religion and/or spiritual group?" we measured their frequency of scripture reading by asking the question ("how many times did you read religious scripture in the last week?") from @bulbulia2016. Those participants who were not religious were imputed a score of "0"

#### Perceived Discrimination -- Religion (waves: 7-15)

Participants were asked to indicate the extent to which they agree with the statement, "I feel that I am often discriminated against because of my religious/spiritual beliefs." (1 = Strongly Disagree to 7 = Strongly Agree).

#### Religion -- Church (waves: 2-11, 13-15)

Based on participants' frequency of church attendance, we coded whether participants attend a church at least one time per month or not (1 = Yes, 0 = No).

#### Sample Frame (waves: 1-15)

see NZAVS

#### Generation Cohort (waves: 1-15)

We use the Pew Research Centre birth cohort categories [@michaeldimock2019]: Generation Silent (1928-1945), Generation Baby Boomer (1946-1964), Generation X (1965-1980), Generation Y (1981-1996) and Generation Z (1997-2012).

#### Political Orientation (waves: 1-3, 4-15)

We measured participants' political orientation using a single item adapted from @jost2006. Participants were asked to rate how politically liberal versus conservative they see themselves as being (1 = Extremely liberal to 7 = Extremely conservative)

#### "rural_gch2018", (waves: )

see NZAVS, report here

#### "bigger_doms" (waves: )

Developed by combining large census categories (Note Inkuk there will not be a reference for this variable -- so no citation)

#### sample_weights (waves: )

(note inkuk we use "w_gend_age_euro" )

#### Short-Form Subjective Health (waves: 5-15)

Participants' subjective health was assessed by three items selected from the MOS 36-item short-form health survey [@warejr1992]. The items were (1) "In general, would you say your health is..."; (2) "I seem to get sick a little easier than most people."; (3) "I expect my health to get worse." Participants responded to those items on a scale (1 = Poor to 7 = Excellent). The second and third items were negatively-worded, so we reversed the responses.

#### Work-Life Balance (waves: 12-13)

Participants indicated the extent to which they agree with the statement, "I have a good balance between work and other important things in my life." (1 = Strongly Disagree to 7 = Strongly Agree).

#### Individual Permeability (waves: 9-13)

Participants indicated the extent to which they agree with the statement, "I believe I am capable, as an individual of improving my status in society.", from @tausch2015 (1 = Strongly Disagree to 7 = Strongly Agree).

\pagebreak

#### References

::: {#refs}
:::
