% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn,
  9pt]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,bottom=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{cancel}
\usepackage[noblocks]{authblk}
\renewcommand*{\Authsep}{, }
\renewcommand*{\Authand}{, }
\renewcommand*{\Authands}{, }
\renewcommand\Affilfont{\small}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal effects of owning pets on multi-dimensional well-being},
  pdfauthor={Marc Wilson; Chris G. Sibley; Joseph A. Bulbulia},
  pdfkeywords={Authors to be added/ order TBA., Cats, Dogs},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal effects of owning pets on multi-dimensional well-being}


  \author{Marc Wilson}
            \affil{%
                  Victoria University of Wellington, New Zealand
              }
        \author{Chris G. Sibley}
            \affil{%
                  School of Psychology, University of Auckland
              }
        \author{Joseph A. Bulbulia}
            \affil{%
                  Victoria University of Wellington, New Zealand
              }
      
\date{}
\begin{document}
\maketitle
\begin{abstract}
This study rigorously assesses the causal impact of pet ownership,
specifically acquiring cats or dogs, on various dimensions of human
well-being among New Zealanders. Using data from the New Zealand
Attitudes and Values Study (NZAVS) spanning 2015 to 2020, we employ a
robust methodological framework for causal inference. Our framework
incorporates targeted machine learning models to balance confounders and
doubly-robust methods for causal estimation, utilising Targeted Maximum
Likelihood Estimation (TMLE). Cat ownership: results offer only
provisional and weak evidence for causal effects of cat ownership on
health and well-being, notably a loss of sleep. Dog ownership: results
offer only provisional and weak evidence for causal effects of cat
ownership on health and well-being, namely: greater exercise. The study
has implications for understanding the complexities of causal
relationships in non-experimental settings where randomised experiments
are not feasible and offers a template for future research in the area
of pet ownership and psycho-social well-being.
\end{abstract}
\subsection{Introduction}\label{introduction}

Whether pets benefit their owners is a question of perennial fascination
and debate. Research abounds on the physical and psychological effects
of pet ownership, often highlighting benefits such as reduced stress
levels, increased physical activity, and better overall well-being.
However, the majority of these studies, including our own previous work
(\citeproc{ref-fraser2020}{Fraser \emph{et al.} 2020b}), rely heavily on
correlational analyses. Thus, questions concerning the causal impact of
pet ownership on human health and psychological well-being remain
unanswered.

Traditional studies, even those of longitudinal design, have been
limited in establishing causality for several reasons:

First, pet ownership cannot be randomised. For example ethical
considerations prohibit the random allocation of pets to households.
However, absent randomisation we cannot fully ensure that association
between pet ownership and well-being is causal.

Second, and relatedly, there are numerous confounding variables that can
affect both pet ownership and the outcomes under study, such as
socio-economic status, lifestyle, and health status. Such confounders
may introduce bias, making it challenging to isolate the specific
effects of pet ownership.

Third, large scale panel datasets are rare; where they exist, they have
yet to be employed to address causality. Opportunities for causal
analysis await.

Here, to address these limitations and provide a robust methodological
framework for causal inference, we adopt the following strategies:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Clarify the causal question:} prior to any analysis, it is
  crucial to explicitly define the causal question under scrutiny.
  Within the umbrella term of ``pet ownership,'' multiple scenarios can
  be considered: coming to own a cat, coming to own a dog, coming to own
  other animals, parting with one or several types of pet, and so forth.
  Here, for the sake of causal clarity, we focus on two population
  average treatment effects: (a) the impact of acquiring cats and (b)
  the impact of acquiring dogs. Each scenario is conceptualised as a
  randomised experiment, contrasting a population that acquires the
  animal with one that does not. Effects are summarised for the
  population.
\item
  \textbf{Clearly define the target population}: the study's findings
  are intended to generalise to New Zealanders from the baseline wave
  2015 of the New Zealand Attitudes and Values Study (NZAVS), who may
  have acquired or lost pets in the next available wave for which the
  NZAVS has measures of pet ownership: NZAVS wave 2019. We measure the
  outcomes as ``intention-to-treat'' effects in NZAVS wave 2020, and
  apply population weights from the New Zealand Census for year wave
  2020 to obtain valid estimates for the New Zealand population in
  2020-2021.
\item
  \textbf{Ensure correct temporal order in the variables}: the study's
  design incorporates a clear temporal structure for confounders and
  outcomes. Confounders are assessed prior to the treatment, negating
  the risk of post-treatment bias. Outcomes pertaining to well-being are
  evaluated after the treatment, thereby reducing the potential for
  reverse causation. This structure underpins the causal flow from pet
  ownership to well-being.
\item
  \textbf{Balance confounders}: once the temporal structure is set, we
  adjust for confounders that could distort the causal link between pet
  ownership and well-being. We employ doubly-robust methods using the
  \texttt{lmtp} package in R (\citeproc{ref-williams2021}{Williams and
  Díaz 2021}). These methods amalgamate targeted machine learning models
  for both the treatment and the outcome variables. Being doubly robust,
  the analysis can recover consistent causal estimates even if either
  model is misspecified (\citeproc{ref-hoffman2023}{Hoffman \emph{et
  al.} 2023}).
\item
  \textbf{Include of baseline measures of the treatment and outcome}:
  after confounder adjustment, we introduce baseline measures for both
  the treatment and the outcomes. This strategy serves two objectives:
  first, it augments control for confounding variables, and second, it
  permits differentiation between ``incidence'' and ``prevalence''
  effects. \emph{Incidence effects} capture the emergence of new cases
  or conditions among individuals who acquire pets during the study.
  This facilitates an evaluation of the causal impact of pet adoption on
  well-being among those who were not pet owners at the baseline.
\item
  \textbf{Assess multiple dimensions of well-being}: we use an
  outcomewide approach (\citeproc{ref-vanderweele2020}{VanderWeele
  \emph{et al.} 2020}) to assess well-being effects across multiple
  dimensions within the same study. This approach has several benefits.
  First we obtain \emph{contextualised effects}: each outcome is
  evaluated in context relative to the others. This facilitates a better
  understanding of the importance of each individual effect within the
  overarching construct of well-being. Second, we \emph{mitigate} of
  spurious findings: by assessing multiple outcomes simultaneously, we
  minimise the risk of cherry-picking cases that confirm a preconceived
  hypothesis, thereby reducing the likelihood of chance findings. Third,
  we \emph{accelerate sientific understanding}: a comprehensive
  assessment can fast-track our scientific insights into the potential
  advantages and disadvantages of pet ownership on various aspects of
  human well-being. The selection of outcomes below are based on
  previous studies reflecting interest in the relationship between pet
  ownership and (1) health, (2) embodied well-being and distress, (3)
  reflective well-being and (4) social well-being.
\item
  \textbf{Obtain methodological precision through TMLE and machine
  learning}: to address the intrinsic limitations of non-randomised pet
  ownership, our study employs Targeted Maximum Likelihood Estimation
  (TMLE) coupled with machine learning techniques (the
  \texttt{SuperLearner} library in R (\citeproc{ref-polley2023}{Polley
  \emph{et al.} 2023})). These advanced methodological enhancement offer
  the following benefits. First, our approach \emph{reduces model
  dependence}: TMLE allows for doubly-robust causal inference, reducing
  reliance on correct model specification. The method is robust even if
  either the treatment model (i.e., pet ownership) or the outcome model
  (i.e., well-being indicators) is incorrectly specified. Second,
  \emph{machine Learning for confounder balancing improves precision}
  further refines our ability to balance confounders, particularly when
  these are high-dimensional or interact in complex ways. Flexible
  semi-parametric estimation of parameters that are of no intrinsic
  interest (the control variables) protects inference from model
  mis-specification (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
  2021}).
\end{enumerate}

Collectively, this approach help us to contribute to a deeper, more
rigorous understanding of the causal relationship between cat or dog
ownership and human well-being.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS) is an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. The
NZAVS began in 2009. It includes questionnaire responses from more
almost 70,000 New Zealand residents. The study includes researchers from
many New Zealand universities, including the University of Auckland,
Victoria University of Wellington, the University of Canterbury, the
University of Otago, and Waikato University. Because the survey asks the
same people to respond each year, it can track subtle change in
attitudes and values over time, and is an important resource for
researchers both in New Zealand and around the world. The NZAVS is
university-based, not- for-profit and independent of political or
corporate funding.https://doi.org/10.17605/OSF.IO/75SNB

\subsubsection{Assumptions for causal
inference}\label{assumptions-for-causal-inference}

In this study, we aim to find out if changing one thing (an
intervention) would cause a different outcome. However, in reality, we
can only observe what happens when we intervene, not what would have
happened if we did not, or vice versa. So we face a fundamental problem
in showing cause and effect directly. To get around this, we estimate a
population aaverage treatment effect (PATE), which compares the average
outcomes of those who received the intervention and those who did not.

For us to say something is a cause, we rely on three important
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal consistency}: this means we expect the outcome we see
  to match what would have happened if the intervention was given. We
  also presume there is no interference between individual cases,
  meaning each person's outcome only depends on whether they received
  the intervention or not. This assumption might not hold if our
  intervention is not well-defined or its meaning is unclear.
\item
  \textbf{Exchangability}: this involves us assuming that whether or not
  someone received the intervention does not affect their potential
  outcomes, once we consider certain observed factors. This is akin to
  how psychologists would randomly assign people to experimental
  conditions. When using real-world data, we mimic this random
  assignment by considering factors that could link the intervention and
  the outcome without any causal relation.
\item
  \textbf{Positivity}: This refers to our expectation that there is
  always a chance for someone to receive or not receive the
  intervention, regardless of other factors. There are two ways this can
  be violated \emph{Random non-positivity} happens when we think there's
  a causal effect for an observation that is missing, which we can check
  using the data. \emph{Deterministic non-positivity} occurs when a
  causal effect is unthinkable. For example, it is generally impossible
  to consider the causal effect of a procedure like a hysterectomy for
  biological males.
\end{enumerate}

These assumptions help us build a fair and meaningful comparison between
those who received the intervention and those who did not. The goal is
to learn about the intervention's overall effect, even though we cannot
directly observe what would have happened without it.

\subsubsection{Causal identification
strategy}\label{causal-identification-strategy}

Effects must follow causes. To avoid the problems of reverse causation,
we measured outcomes during the year following the exposure (NZAVS wave
2020). The causal graph presented in Figure~\ref{fig-outcomewide-dag}
describes our method for confouding control. We follow VanderWeele
\emph{et al.} (\citeproc{ref-vanderweele2020}{2020}) in adopting a
modified disjunctive cause criterion which states:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Identify all relevant factors}: first, find every covariates
  that can influence either the exposure or the outcomes (across the
  five domains), or both. These factors are any variable that can have
  an impact on the exposure or outcome, are that might be the effect of
  such a factor.
\item
  \textbf{Remove instrumental variables}: next, take out any factors
  that are known to be `instrumental variables'. These are factors that
  cause the exposure but do not affect the outcome. Including
  instrumental variables reduces efficiency.
\item
  \textbf{Include proxy variables for unmeasured common causes}: if
  there are any unmeasured factors that influence both the exposure and
  outcome, but we don not have direct measurements for them, we should
  try to include a proxy for these. A proxy is an effect of the
  variable.
\item
  \textbf{Control for prior exposure}: Controlling for prior exposure
  assesses the effects of ``incident exposure'' rather than ``prevalent
  exposure'' - and is a critical step in causal
  inference(\citeproc{ref-danaei2012}{Danaei \emph{et al.} 2012};
  \citeproc{ref-hernan2023}{Hernan and Robins 2023}). By including prior
  exposure in the analysis, we can more effectively emulate a controlled
  trial. This approach not only helps interpret the effect of exposure
  changes but also strengthens confounding control. It aids in avoiding
  reverse causation and managing other forms of unmeasured confounding.
  This setup ensures that any unmeasured confounder would have to
  influence both the outcome and initial exposure, irrespective of
  previous exposure levels, to explain an observed exposure-outcome
  association.
\item
  \textbf{Control for prior outcome}: It is also vital to control for
  the outcome measured at baseline -- the `baseline outcome'. This
  tactic aims to rule out reverse causation by ensuring that the
  cause-effect relationship follows the right temporal order. Even
  though it does not eliminate the possibility of reverse causation,
  controlling for the baseline outcome helps mitigate its effects.
  Hence, along with a rich set of covariates, the baseline outcome
  should be included in the covariate set to make the confounding
  control assumption as plausible as possible. It is often the strongest
  confounder affecting both the exposure and subsequent outcome. (For a
  detailed account of confounding control in three-wave panel designs
  see VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020}))
\end{enumerate}

To avoid bias, we must also handle missing data arising from
non-response or panel attrition (loss-to-follow up). Again, to address
selection bias at baseline we imputated missing values using the
\texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van Buuren
2018}). To handling non-response/ missingness at follow-up we used
censoring weights, which were passed to the semi-parametric models.
Valid inferences for the New Zealand population were obtained by passing
post-stratification census weights (Age, European Ethnicity, Gender).

\subsubsection{Study 1: eligibility criteria for inclusion in the causal
effects of cat
ownership}\label{study-1-eligibility-criteria-for-inclusion-in-the-causal-effects-of-cat-ownership}

The sample consisted of respondents to NZAVS waves 2015 (baseline), 2019
(exposure wave), and 2020 (outcome wave) (years 2015-2021) (See Appendix
A.)

\paragraph{Inclusion Criteria}\label{inclusion-criteria}

\begin{itemize}
\tightlist
\item
  Participants who provided full information provided about pets at
  baseline and the exposure wave (NZAVS wave 2019)
\item
  Participants with missing data for all variables at baseline were
  allowed. Missing data were multiply imputed through the \texttt{mice}
  package (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  Participants without pets at baseline or those with cats.
\item
  Participants without pets or those with cats at the exposure wave
  (NZAVS wave 2019).
\end{itemize}

\paragraph{Exclusion Criteria}\label{exclusion-criteria}

\begin{itemize}
\tightlist
\item
  Participants who had any other pets at baseline (wave 2015) or the
  exposure wave (NZAVS wave 2019) other than cats.
\item
  We allowed loss-to-follow up in the outcome wave (NZAVS wave 2020);
  missing values owing to attrition and non-response were were handled
  using censoring weights (see details of the \texttt{lmtp} package
  (\citeproc{ref-williams2021}{Williams and Díaz 2021})).
\end{itemize}

There were 5376 NZAVS participants who met these criteria.

\subsubsection{Study 1 exposure: positivity for cat
ownership}\label{study-1-exposure-positivity-for-cat-ownership}

Table~\ref{tbl-transition} is a transition matrix describes the shifts
from one state of meaning of life to another state between the baseline
wave and the following wave. The numbers in the cells represent the
number of individuals who transitioned from one state (rows) to another
(columns). For example, the cell in the first row and second column
shows the number of individuals who transitioned from the first state
(indicated by the left-most cell in the row) to the second state. The
top left cell shows the number of individuals who remained in the first
state. We find evidence for both change in the exposure between the
baseline wave and the exposure wave (wave 18) among the 5376
participants, thus satisifying the positivity assumpition (see below).

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in cat ownership from baseline to
to the exposure wave}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
From & No Cats & Cats \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & No Cats & Cats \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No Cats & 2781 & 287 \\
Cats & 539 & 1769 \\
\end{longtable}

\subsubsection{Study 2: eligibility criteria for the causal effects of
dog
ownership}\label{study-2-eligibility-criteria-for-the-causal-effects-of-dog-ownership}

The sample consisted of respondents to NZAVS waves 2015 (baseline), 2019
(exposure wave), and 2020 (outcome wave) (years 2015-2021) (See Appendix
A.)

Inclusion criteria for the cats an dogs analysis were the same as for
the cats analysis, replacing ``dogs'' for ``cats''. There were 4132
NZAVS participants who met these criteria.

\subsubsection{Study 2 exposure: positivity for dog
ownership}\label{study-2-exposure-positivity-for-dog-ownership}

Table~\ref{tbl-transition-dogs} is a transition matrix describes the
shifts from one state of meaning of life to another state between the
baseline wave and the following wave. The numbers in the cells represent
the number of individuals who transitioned from one state (rows) to
another (columns). For example, the cell in the first row and second
column shows the number of individuals who transitioned from the first
state (indicated by the left-most cell in the row) to the second state.
The top left cell shows the number of individuals who remained in the
first state. We find evidence for both change in the exposure between
the baseline wave and the exposure wave (wave 18) among the 5376
participants, thus satisifying the positivity assumpition (see below).

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in cat ownership from baseline to
to the exposure wave}\label{tbl-transition-dogs}\tabularnewline
\toprule\noalign{}
From & No Dogs & Dogs \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & No Dogs & Dogs \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No Dogs & 2781 & 183 \\
Dogs & 215 & 953 \\
\end{longtable}

\subsubsection{Multi-dimensional indicators of
well-being}\label{multi-dimensional-indicators-of-well-being}

We assessed well-being following VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020}) outcome-wide template.
Outcomewide studies argue that, rather than cherry-picking one or
several domains of well-being, science may advance more rapidly, and
with greater hope for replication, by assess well-being across as many
range of indicators the data may afford. To assist with interpretation,
VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020}) groups
well-being into larger dimensions of interest. Here, we identify
five-domains: health, embodied well-being, practical well-being,
reflective well-being, and social well-being (see Appendix A.)

\newpage{}

\begin{figure}

\centering{

\includegraphics[width=0.8\textwidth,height=\textheight]{man-lmtp-ow-fl-pets_files/figure-pdf/fig-outcomewide-dag-1.pdf}

}

\caption{\label{fig-outcomewide-dag}Causal graph: three-wave panel
design with selection bias. By controling for confounding at baseline we
block back-door paths that might lead to an association between the
treatment and the outcome. Adding previous measurments of the exposure
and outcome at baseline further reduces confounding. Nevertheless,
because we cannot ensure all confounding paths have been blocked, we
perform sensitivity analysis. These allow us to ask, how strong would
the unmeasured confounder need to be in its association with the
treatment and the outcome to explain away the observed association.}

\end{figure}%

\newpage{}

\subsubsection{Statistical Estimation: Targeted Maximum Likelihood and
Longitudinal Modified Treatment
Policies}\label{statistical-estimation-targeted-maximum-likelihood-and-longitudinal-modified-treatment-policies}

To assess the causal impact of pet ownership on well-being, our analysis
employs Targeted Maximum Likelihood Estimation (TMLE) for doubly-robust
causal inference. This method integrates both treatment models and
outcome models, enhancing the study's resilience against model
misspecification.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Treatment model with propensity scores}: The initial step in
  our analytical pipeline involves the calculation of propensity scores
  for each participant. These scores represent the likelihood of an
  individual acquiring a pet, conditioned on their covariates. We derive
  these scores from a targeted machine learning model, which
  incorporates high-dimensional confounders to estimate the likelihood
  of treatment assignment (i.e., pet ownership).
\item
  \textbf{Weighting via propensity scores}: Post-calculation of
  propensity scores, each individual in the dataset is assigned a
  weight. These weights are inverse probability weights and serve to
  balance the distribution of observed covariates between treated and
  untreated groups, thereby reducing the bias in causal estimates.
\item
  \textbf{Outcome models focused on well-being}: Subsequently, we
  develop a second targeted machine learning model concentrating on the
  outcome variables, which encompass approximately 15 measures of
  well-being across five domains. This model incorporates both the
  treatment status (pet ownership) and the aforementioned weights,
  refining our ability to make causal inferences.
\item
  \textbf{Counterfactual contrasts}: Central to TMLE is the prediction
  of counterfactual outcomes. Utilising the estimates from both
  treatment and outcome models, TMLE facilitates the prediction of what
  the well-being measures would have been for each individual under both
  treatment conditions---owning a pet and not owning a pet.
\item
  \textbf{Effect estimation}: Finally, we compute the average treatment
  effect by contrasting these counterfactual outcomes. Specifically, we
  calculate the difference in predicted well-being between the two
  treatment levels---having a pet versus not having one.
\end{enumerate}

The integration of TMLE and machine learning mitigates reliance on
stringent modelling assumptions and adds an extra layer of robustness,
making this a particularly rigorous approach for causal inference in the
study of pet ownership and human well-being. (For further details see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023})

\subsubsection{Shift estimand for Longitudional Modified Treatment
Strategies}\label{shift-estimand-for-longitudional-modified-treatment-strategies}

Here, we employ a ``shift'' estimand, a distinct alternative to
traditional causal estimands that typically compare the impact of
setting everyone to one exposure level against
another(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021}). The shift
estimand facilitates clearer comparisons of hypothetical interventions
required for causal inference. Here, we examine the effect of universal
pet ownership - cats in Study 1 an and dogs in Study 2 -- against the
natural course of either owning or not owning a pet. We operationalise
this approach using the \texttt{lmtp} package in R
(\citeproc{ref-williams2021}{Williams and Díaz 2021}). One of the merits
of using a shift estimand is its potential to yield more actionable
policy insights. Specifically, it enables us to address questions such
as, ``What would occur if everyone were to adopt pet ownership?''
without necessitating a strong counterfactual scenario where all
individuals are forced to relinquish pet ownership for the sake of
causal contrast.

Furthermore, the shift approach alleviates some of the stringency
associated with positivity assumptions. Enacting an intervention to
compel people to give up their pets might not be plausible, either
ethically or logistically. The shift estimand, therefore, offers a more
reasonable and achievable analytical frame. Additionally, as
demonstrated in Appendix C, the shift estimand exhibits marginally
greater conservatism in estimates. This feature adds an additional layer
of robustness to our findings, making them more reliable for policy
considerations.

\newpage{}

\subsection{Study 1 Results: Cat
Ownership}\label{study-1-results-cat-ownership}

\subsubsection{Effects on health}\label{effects-on-health}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-health-cats-1.pdf}

}

\caption{\label{fig-results-health-cats}Causal effects on health}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-health-cats}Table of results for the health
domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3735}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1928}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0964}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0964}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0964}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1446}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Short form health, your health & -0.0250 & -0.0604 & 0.0103 & 1.1764 &
1.0000 \\
Hours excercise & -0.0076 & -0.0493 & 0.0341 & 1.0905 & 1.0000 \\
Alcohol frequency & 0.0136 & -0.0152 & 0.0424 & 1.1247 & 1.0000 \\
Alcohol intensity & -0.0014 & -0.0352 & 0.0325 & 1.0370 & 1.0000 \\
Hours sleep & -0.0573 & -0.0963 & -0.0183 & 1.2910 & 1.1478 \\
BMI & 0.0064 & -0.0130 & 0.0258 & 1.0825 & 1.0000 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Table~\ref{tbl-results-health-cats} and
Table~\ref{tbl-results-health-cats} presents the Population Average
Treatment Effect (PATE) which is the expected difference in outcomes
between treatment and control groups for the New Zealand population. We
observed the following:

For the outcome `Alcohol frequency', the PATE causal contrast is 0.014.
The confidence interval ranges from -0.015 to 0.042. The E-value for
this outcome is 1.125, indicating no reliable evidence for causality.

For the outcome `BMI', the PATE causal contrast is 0.006. The confidence
interval ranges from -0.013 to 0.026. The E-value for this outcome is
1.082, indicating no reliable evidence for causality.

For the outcome `Alcohol intensity', the PATE causal contrast is -0.001.
The confidence interval ranges from -0.035 to 0.032. The E-value for
this outcome is 1.037, indicating no reliable evidence for causality.

For the outcome `Hours excercise', the PATE causal contrast is -0.008.
The confidence interval ranges from -0.049 to 0.034. The E-value for
this outcome is 1.09, indicating no reliable evidence for causality.

For the outcome `Short form health, your health', the PATE causal
contrast is -0.025. The confidence interval ranges from -0.06 to 0.01.
The E-value for this outcome is 1.176, indicating no reliable evidence
for causality.

For the outcome `Hours sleep', the PATE causal contrast is -0.057. The
confidence interval ranges from -0.096 to -0.018. The E-value for this
outcome is 1.291, indicating reliable evidence for causality.

\newpage{}

\subsubsection{Effects on embodied
well-being}\label{effects-on-embodied-well-being}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-embodied-cats-1.pdf}

}

\caption{\label{fig-results-embodied-cats}Causal effects on embodied
well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-embodied-cats}Table of results for the
embodied well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Body satisfaction & -0.0254 & -0.0609 & 0.0101 & 1.1781 & 1 \\
Kessler 6 distress & 0.0016 & -0.0291 & 0.0323 & 1.0397 & 1 \\
Fatigue & 0.0219 & -0.0150 & 0.0588 & 1.1634 & 1 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-embodied-cats} and
Table~\ref{tbl-results-embodied-cats} presents the Population Average
Treatment Effect (PATE) for the embodied domain.

For the outcome `Fatigue', the PATE causal contrast is 0.022. The
confidence interval ranges from -0.015 to 0.059. The E-value for this
outcome is 1.163, indicating no reliable evidence for causality.

For the outcome `Kessler 6 distress', the PATE causal contrast is 0.002.
The confidence interval ranges from -0.029 to 0.032. The E-value for
this outcome is 1.04, indicating no reliable evidence for causality.

For the outcome `Body satisfaction', the PATE causal contrast is -0.025.
The confidence interval ranges from -0.061 to 0.01. The E-value for this
outcome is 1.178, i indicating no reliable evidence for causality.

\newpage{}

\subsubsection{Effects on reflective
well-being}\label{effects-on-reflective-well-being}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-reflective-well-being-cats-1.pdf}

}

\caption{\label{fig-results-reflective-well-being-cats}Causal effects on
reflective well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-reflective-cats}Table of results for the
reflective well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3247}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2078}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1039}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1039}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1039}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1558}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Self esteem & -0.0174 & -0.0471 & 0.0124 & 1.1433 & 1.0000 \\
PWB your health & -0.0208 & -0.0571 & 0.0156 & 1.1587 & 1.0000 \\
PWB your future security & -0.0009 & -0.0390 & 0.0371 & 1.0295 &
1.0000 \\
PWB your relationships & -0.0384 & -0.0757 & -0.0011 & 1.2275 &
1.0347 \\
PWB your standard living & -0.0018 & -0.0400 & 0.0365 & 1.0422 &
1.0000 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-reflective-well-being-cats} and
Table~\ref{tbl-results-reflective-cats} presents the Population Average
Treatment Effect (PATE) for the reflective domain.

For the outcome `PWB your future security', the PATE causal contrast is
-0.001. The confidence interval ranges from -0.039 to 0.037. The E-value
for this outcome is 1.03, indicating no reliable evidence for causality.

For the outcome `PWB your standard living', the PATE causal contrast is
-0.002. The confidence interval ranges from -0.04 to 0.036. The E-value
for this outcome is 1.042, indicating no reliable evidence for
causality.

For the outcome `Self esteem', the PATE causal contrast is -0.017. The
confidence interval ranges from -0.047 to 0.012. The E-value for this
outcome is 1.143, indicating no reliable evidence for causality.

For the outcome `PWB your health', the PATE causal contrast is -0.021.
The confidence interval ranges from -0.057 to 0.016. The E-value for
this outcome is 1.159, indicating no reliable evidence for causality.

For the outcome `PWB your relationships', the PATE causal contrast is
-0.038. The confidence interval ranges from -0.076 to -0.001. The
E-value for this outcome is 1.228, indicating evidence for causality is
weak.

\newpage{}

\subsubsection{Effects on social
well-being}\label{effects-on-social-well-being}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-social-wellbeing-cats-1.pdf}

}

\caption{\label{fig-results-social-wellbeing-cats}Causal effects on
social well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-social-cats}Table of results for the
reflective well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3200}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2133}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1067}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0933}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1067}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1600}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Social support & -0.0236 & -0.0576 & 0.0104 & 1.1706 & 1 \\
Neighbourhood community & 0.0091 & -0.0284 & 0.0465 & 1.0999 & 1 \\
Social belonging & -0.0113 & -0.0435 & 0.0209 & 1.1125 & 1 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-social-wellbeing-cats} and
Table~\ref{tbl-results-social-cats} present the results of the social
well-being analysis.

For the outcome `Neighbourhood community', the PATE causal contrast is
0.009. The confidence interval ranges from -0.028 to 0.046. The E-value
for this outcome is 1.1, indicating no reliable evidence for causality.

For the outcome `Social belonging', the PATE causal contrast is -0.011.
The confidence interval ranges from -0.044 to 0.021. The E-value for
this outcome is 1.112, indicating no reliable evidence for causality..

For the outcome `Social support', the PATE causal contrast is -0.024.
The confidence interval ranges from -0.058 to 0.01. The E-value for this
outcome is 1.171, indicating no reliable evidence for causality.

\subsubsection{Discussion: Causal effects of cat ownership on
multi-dimensional
well-being}\label{discussion-causal-effects-of-cat-ownership-on-multi-dimensional-well-being}

Our analyses reveals little evidence to support strong causal claims
about the impact of owning a cat, for those who previously did not own
cats, on multiple dimensions of well-being. The Population Average
Treatment Effects (PATE) across outcomes largely hovered around zero,
with confidence intervals spanning both sides of the null.

\begin{itemize}
\item
  \textbf{General Trends}: across domains such as alcohol consumption,
  body mass index, exercise, and psychological well-being, PATE causal
  contrasts were small and accompanied by E-values that suggest no
  reliable evidence for causality. This held true for outcomes like
  alcohol frequency, BMI, exercise hours, and several facets of
  psychological well-being.
\item
  \textbf{Sleep}: the outcome that stood apart was `Hours sleep: Gain
  cat if not have pets'. Here, the PATE causal contrast was -0.057 with
  a confidence interval ranging from -0.096 to -0.018. The associated
  E-value of 1.291 suggests that there is reliable evidence for
  causality. However, the evidence only provisionally supports the
  notion that gaining a cat may lead to a reduction in sleep hours, and
  even here the effect size is modest.
\item
  \textbf{Outliers}: another outcome worth noting is `PWB your
  relationships: Gain cat if not have pets', which had a PATE causal
  contrast of -0.038. Though the E-value of 1.228 indicates weak
  evidence for causality, this could be an area for further
  investigation.
\end{itemize}

The results thus prompt caution in making substantive claims about the
causal impacts of pet ownership, particularly in gaining a cat, on
well-being for the New Zealand population. Further research is warranted
to corroborate or refute these preliminary findings.

\newpage{}

\subsection{Study 2 Results Dog
Ownership}\label{study-2-results-dog-ownership}

\subsubsection{Effects on Health}\label{effects-on-health-1}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-health-dogs-1.pdf}

}

\caption{\label{fig-results-health-dogs}Causal effects on embodied
well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-health-dogs}Table of results for the health
domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3780}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1951}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0976}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0854}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0976}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1463}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Short form health, your health & -0.0389 & -0.1000 & 0.0222 & 1.2292 &
1.000 \\
Hours excercise & 0.0742 & 0.0068 & 0.1417 & 1.3432 & 1.086 \\
Alcohol frequency & -0.0289 & -0.0819 & 0.0240 & 1.1921 & 1.000 \\
Alcohol intensity & 0.0222 & -0.0321 & 0.0764 & 1.1647 & 1.000 \\
Hours sleep & -0.0355 & -0.1005 & 0.0296 & 1.2170 & 1.000 \\
BMI & 0.0162 & -0.0185 & 0.0510 & 1.1376 & 1.000 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-health-dogs} and
Table~\ref{tbl-results-health-dogs} presents the Population Average
Treatment Effect (PATE) which is the expected difference in outcomes
between treatment and control groups for the New Zealand population. We
observed the following:

For the outcome `Hours excercise', the PATE causal contrast is 0.074.
The confidence interval ranges from 0.007 to 0.142. The E-value for this
outcome is 1.343, indicating reliable evidence for causality.

For the outcome `Alcohol intensity', the PATE causal contrast is 0.022.
The confidence interval ranges from -0.032 to 0.076. The E-value for
this outcome is 1.165, indicating no reliable evidence for causality.

For the outcome `BMI', the PATE causal contrast is 0.016. The confidence
interval ranges from -0.018 to 0.051. The E-value for this outcome is
1.138, indicating no reliable evidence for causality. weak.

For the outcome `Alcohol frequency', the PATE causal contrast is -0.029.
The confidence interval ranges from -0.082 to 0.024. The E-value for
this outcome is 1.192, indicating no reliable evidence for causality.

For the outcome `Hours sleep', the PATE causal contrast is -0.035. The
confidence interval ranges from -0.1 to 0.03. The E-value for this
outcome is 1.217, indicating no reliable evidence for causality.

For the outcome `Short form health, your health', the PATE causal
contrast is -0.039. The confidence interval ranges from -0.1 to 0.022.
The E-value for this outcome is 1.229, no reliable evidence for
causality.

\newpage{}

\subsubsection{Effects on embodied
well-being}\label{effects-on-embodied-well-being-1}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-embodied-dogs-1.pdf}

}

\caption{\label{fig-results-embodied-dogs}Causal effects on embodied
well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-embodied-dogs}Table of results for the
embodied well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Body satisfaction & -0.0310 & -0.0943 & 0.0323 & 1.2002 & 1 \\
Kessler 6 distress & 0.0281 & -0.0291 & 0.0852 & 1.1889 & 1 \\
Fatigue & 0.0317 & -0.0344 & 0.0977 & 1.2028 & 1 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-embodied-dogs} and
Table~\ref{tbl-results-embodied-dogs} presents the Population Average
Treatment Effect (PATE) for the embodied domain.

For the outcome `Fatigue', the PATE causal contrast is 0.032. The
confidence interval ranges from -0.034 to 0.098. The E-value for this
outcome is 1.203, indicating no reliable evidence for causality.

For the outcome `Kessler 6 distress', the PATE causal contrast is 0.028.
The confidence interval ranges from -0.029 to 0.085. The E-value for
this outcome is 1.189,indicating no reliable evidence for causality.

For the outcome `Body satisfaction', the PATE causal contrast is -0.031.
The confidence interval ranges from -0.094 to 0.032. The E-value for
this outcome is 1.2,indicating no reliable evidence for causality.

\newpage{}

\subsubsection{Effects on reflective
well-being}\label{effects-on-reflective-well-being-1}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-reflective-well-being-dogs-1.pdf}

}

\caption{\label{fig-results-reflective-well-being-dogs}Causal effects on
reflective well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-reflective-dogs}Table of results for the
reflective well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3289}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2105}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1053}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0921}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1053}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1579}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Self esteem & -0.0337 & -0.0884 & 0.0209 & 1.2103 & 1 \\
PWB your health & -0.0292 & -0.0949 & 0.0365 & 1.1932 & 1 \\
PWB your future security & -0.0597 & -0.1305 & 0.0110 & 1.2986 & 1 \\
PWB your relationships & -0.0127 & -0.0749 & 0.0496 & 1.1201 & 1 \\
PWB your standard living & 0.0333 & -0.0301 & 0.0968 & 1.2088 & 1 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-reflective-well-being-dogs} and
Table~\ref{tbl-results-reflective-dogs} presents the Population Average
Treatment Effect (PATE) for the reflective domain.

For the outcome `PWB your standard living', the PATE causal contrast is
0.033. The confidence interval ranges from -0.03 to 0.097. The E-value
for this outcome is 1.209, indicating no reliable evidence for
causality.

For the outcome `PWB your relationships', the PATE causal contrast is
-0.013. The confidence interval ranges from -0.075 to 0.05. The E-value
for this outcome is 1.12, indicating no reliable evidence for causality.

For the outcome `PWB your health', the PATE causal contrast is -0.029.
The confidence interval ranges from -0.095 to 0.036. The E-value for
this outcome is 1.193, indicating no reliable evidence for causality.

For the outcome `Self esteem', the PATE causal contrast is -0.034. The
confidence interval ranges from -0.088 to 0.021. The E-value for this
outcome is 1.21, indicating no reliable evidence for causality. For the
outcome `PWB your future security', the PATE causal contrast is -0.06.
The confidence interval ranges from -0.13 to 0.011. The E-value for this
outcome is 1.299, indicating no reliable evidence for causality.

\newpage{}

\subsubsection{Effects on social
well-being}\label{effects-on-social-well-being-1}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-results-social-wellbeing-dogs-1.pdf}

}

\caption{\label{fig-results-social-wellbeing-dogs}Causal effects on
social well-being}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-results-social-dogs}Table of results for the
reflective well-being domain}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3200}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2133}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1067}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0933}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1067}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1600}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Social support & -0.0637 & -0.1284 & 0.0011 & 1.3112 & 1 \\
Neighbourhood community & 0.0209 & -0.0381 & 0.0798 & 1.1591 & 1 \\
Social belonging & -0.0153 & -0.0708 & 0.0403 & 1.1333 & 1 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Figure~\ref{fig-results-social-wellbeing-dogs} and
Table~\ref{tbl-results-social-dogs} present the population average
treatement effects for the social domain.

For the outcome `Neighbourhood community', the PATE causal contrast is
0.021. The confidence interval ranges from -0.038 to 0.08. The E-value
for this outcome is 1.159, indicating no reliable evidence for
causality.

For the outcome `Social belonging', the PATE causal contrast is -0.015.
The confidence interval ranges from -0.071 to 0.04. The E-value for this
outcome is 1.133, indicating no reliable evidence for causality.

For the outcome `Social support', the PATE causal contrast is -0.064.
The confidence interval ranges from -0.128 to 0.001. The E-value for
this outcome is 1.311, indicating no reliable evidence for causality.

\subsubsection{Discussion: Causal effects of dog ownership on
multi-dimensional
well-being}\label{discussion-causal-effects-of-dog-ownership-on-multi-dimensional-well-being}

Among the array of outcomes studied in relation to acquiring a dog, only
one indicator provided reliable evidence for a causal effect---exercise.
Specifically, the Population Average Treatment Effect (PATE) for `Hours
exercise' was 0.074, with a confidence interval ranging from 0.007 to
0.142 and an E-value of 1.343. This suggests that gaining a dog leads to
a modest but statistically significant increase in exercise for
individuals who socialise at least two hours per week.

For all other outcomes examined---ranging from body mass index (BMI) and
alcohol consumption to various psychological well-being markers---there
was no reliable evidence supporting a causal relationship. Confidence
intervals for these outcomes generally crossed zero, and E-values fell
short of indicating strong evidence for causality.

In summary, our study provides limited support for the proposition that
acquiring a dog causally affects human well-being, with evidence
restricted to exercise levels.

\subsection{General Discussion}\label{general-discussion}

\subsubsection{Summary of findings}\label{summary-of-findings}

The expected diminution of sleep resulting from cat ownership in the
general population is estimated to be about \emph{four minutes} per
night This appears modest, but the level of confidence in this finding
is relatively high. In contrast, the expected augmentation in exercise
from dog ownership is about \emph{ten minutes} per week. The size of
this effect may appear modest but is backed by relatively strong
evidence.

Note further that the modest effect sizes found in our analyses,
particularly a loss of about ten minutes of sleep per week for cat
owners and an increase of approximately four minutes of exercise per
night for dog owners, should be interpreted with caution. Our study sets
a high bar for evidence, relying on robust statistical methods that
control for confounding variables and strive for generalisability.
However, the Population Average Treatment Effects (PATE) reported are
just that---averages across the population contrasting ownership with
what would have been observed, on average, had there been no shift in
ownership.

\subsubsection{Assumptions and
limitations}\label{assumptions-and-limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causality and confounding}: we employs rigorous causal
  inference techniques, but these are contingent on the assumption of no
  unmeasured confounding. (Say more about E-values)
\item
  \textbf{Measurement error}: the variables under
  consideration---exercise and sleep---are self-reported, which might
  introduce both systematic and random measurement errors. It should be
  specifically noted that the apparent modesty of the practical effects
  could arise, in part, to measurement inaccuracy. Given the limitations
  of self-report measures, the true effect sizes may differ from those
  estimated. Therefore, while the evidence does suggest a modest impact,
  the actual real-world effects may be either smaller or larger than the
  estimates suggest. Given the modest effect sizes and the limitations
  of self-report measures, future research should explore the use of
  more objective measures for variables like exercise and sleep.
  (\ldots{} etc.)
\item
  \textbf{Generalisability and transportability}: our findings should be
  interpreted within the context of the New Zealand population from
  which the data were sourced. Although the results may have broader
  relevance, direct extrapolation to different populations or
  sociocultural settings should be undertaken cautiously.
\end{enumerate}

\subsubsection{Theoretical and practical
relevance}\label{theoretical-and-practical-relevance}

This study contributes to an emerging but still limited body of
scholarly work on the causal impacts of pet ownership on various
dimensions of human well-being. Notably, the study employs advanced
causal inference methods, offering a potential methodological framework
for future investigations in this area.

Although the observed effect sizes are modest, they are not necessary
trivial. Decisions around pet ownership should consider the full range
of potential impacts, both positive and negative, on well-being -- and
of course, on the animals themselves. However, it would be premature to
recommend pet ownership as a strategy for large improvements in
well-being, based on the current evidence.

\newpage{}

\subsubsection{Ethics Statement}\label{ethics-statement}

The NZAVS is reviewed every three years by the University of Auckland
Human Participants Ethics Committee. Our most recent ethics approval
statement is as follows: The New Zealand Attitudes and Values Study was
approved by the University of Auckland Human Participants Ethics
Committee on 26/05/2021 for six years until 26/05/2027, Reference Number
UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the TempletoReligion Trust (TRT0196; TRT0418). JB received support from
the Max Planck Institute for the Science of Human History. The funders
had no role in preparing the manuscript or the decision to publish.

\subsubsection{Author Statement}\label{author-statement}

TBA

\newpage{}

\subsection{Appendix A. Descriptive
Tables}\label{appendix-a.-descriptive-tables}

\subsubsection{Baseline confounding control
cats}\label{baseline-confounding-control-cats}

\textbf{?@tbl-baseline-table-cats} presents baseline data for the Study
1: the causal effects of cat ownership on multi-dimensional well-being.
The ``only\_cats'' variable indicates the percentage of participants who
had or did not have cats at baseline. Baseline variables were included
to limit confounding of the the treatment/outcome effect.

\newpage{}

\subsubsection{Baseline confounding control:
cats}\label{baseline-confounding-control-cats-1}

\begin{table}

\caption{\label{tbl-baseline-table-dogs}Baseline demographic and
response statistics for cat ownership study}

\centering{

\begin{longtable}[]{@{}lc@{}}
\toprule\noalign{}
\textbf{Characteristic} & \textbf{N = 4,132} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
only\_dog & \\
0 & 2,964 (72\%) \\
1 & 1,168 (28\%) \\
age & \\
Mean (SD) & 54 (14) \\
agreeableness & \\
Mean (SD) & 5.34 (0.94) \\
alcohol\_frequency & \\
0 & 584 (14\%) \\
1 & 796 (19\%) \\
2 & 743 (18\%) \\
3 & 920 (22\%) \\
4 & 1,076 (26\%) \\
5 & 13 (0.3\%) \\
alcohol\_intensity & \\
Mean (SD) & 1.91 (1.82) \\
belong & \\
Mean (SD) & 5.17 (1.01) \\
bodysat & \\
1 & 219 (5.3\%) \\
2 & 357 (8.6\%) \\
3 & 662 (16\%) \\
4 & 735 (18\%) \\
5 & 871 (21\%) \\
6 & 1,024 (25\%) \\
7 & 264 (6.4\%) \\
born\_nz & \\
0 & 911 (22\%) \\
1 & 3,221 (78\%) \\
children\_num & \\
Mean (SD) & 1.89 (1.52) \\
conscientiousness & \\
Mean (SD) & 5.17 (0.98) \\
education\_level\_coarsen & \\
1 & 117 (2.8\%) \\
2 & 1,352 (33\%) \\
3 & 588 (14\%) \\
4 & 1,094 (26\%) \\
5 & 471 (11\%) \\
6 & 405 (9.8\%) \\
7 & 105 (2.5\%) \\
eth\_cat & \\
1 & 3,314 (80\%) \\
2 & 506 (12\%) \\
3 & 116 (2.8\%) \\
4 & 196 (4.7\%) \\
extraversion & \\
Mean (SD) & 3.88 (1.13) \\
hlth\_bmi & \\
Mean (SD) & 27.1 (5.7) \\
hlth\_disability & \\
0 & 2,881 (70\%) \\
1 & 1,251 (30\%) \\
hlth\_fatigue & \\
0 & 713 (17\%) \\
1 & 1,619 (39\%) \\
2 & 1,223 (30\%) \\
3 & 459 (11\%) \\
4 & 118 (2.9\%) \\
hlth\_sleep\_hours & \\
Mean (SD) & 6.90 (1.12) \\
honesty\_humility & \\
Mean (SD) & 5.47 (1.17) \\
hours\_children\_log & \\
Mean (SD) & 0.97 (1.45) \\
hours\_exercise\_log & \\
Mean (SD) & 1.67 (0.81) \\
hours\_housework\_log & \\
Mean (SD) & 2.18 (0.79) \\
hours\_work\_log & \\
Mean (SD) & 2.43 (1.69) \\
household\_inc\_log & \\
Mean (SD) & 11.31 (0.81) \\
kessler6\_sum & \\
Mean (SD) & 4 (4) \\
lifesat & \\
Mean (SD) & 5.32 (1.17) \\
male & \\
-1 & 1,694 (41\%) \\
0 & 2,438 (59\%) \\
neighbourhood\_community & \\
1 & 108 (2.6\%) \\
2 & 266 (6.4\%) \\
3 & 400 (9.7\%) \\
4 & 741 (18\%) \\
5 & 1,084 (26\%) \\
6 & 1,109 (27\%) \\
7 & 424 (10\%) \\
neuroticism & \\
Mean (SD) & 3.29 (1.11) \\
nz\_dep2018 & \\
Mean (SD) & 4.73 (2.71) \\
nzsei13 & \\
Mean (SD) & 56 (15) \\
openness & \\
Mean (SD) & 4.92 (1.10) \\
partner & \\
0 & 1,152 (28\%) \\
1 & 2,980 (72\%) \\
political\_conservative & \\
1 & 198 (4.8\%) \\
2 & 775 (19\%) \\
3 & 913 (22\%) \\
4 & 1,271 (31\%) \\
5 & 635 (15\%) \\
6 & 289 (7.0\%) \\
7 & 51 (1.2\%) \\
pwb\_standard\_living & \\
Mean (SD) & 7.68 (1.98) \\
pwb\_your\_future\_security & \\
Mean (SD) & 6.48 (2.41) \\
pwb\_your\_health & \\
Mean (SD) & 6.92 (2.27) \\
pwb\_your\_relationships & \\
Mean (SD) & 7.88 (2.17) \\
religion\_church\_round & \\
0 & 3,291 (80\%) \\
1 & 145 (3.5\%) \\
2 & 108 (2.6\%) \\
3 & 99 (2.4\%) \\
4 & 258 (6.2\%) \\
5 & 61 (1.5\%) \\
6 & 44 (1.1\%) \\
7 & 23 (0.6\%) \\
8 & 103 (2.5\%) \\
religion\_identification\_level & \\
1 & 2,468 (60\%) \\
2 & 182 (4.4\%) \\
3 & 142 (3.4\%) \\
4 & 284 (6.9\%) \\
5 & 270 (6.5\%) \\
6 & 251 (6.1\%) \\
7 & 535 (13\%) \\
sample\_origin & \\
1-2 & 1,041 (25\%) \\
3-3.5 & 849 (21\%) \\
4 & 894 (22\%) \\
5-6-7 & 1,348 (33\%) \\
self\_esteem & \\
Mean (SD) & 5.36 (1.16) \\
sfhealth\_your\_health & \\
1 & 23 (0.6\%) \\
2 & 74 (1.8\%) \\
3 & 259 (6.3\%) \\
4 & 499 (12\%) \\
5 & 1,072 (26\%) \\
6 & 1,565 (38\%) \\
7 & 640 (15\%) \\
smoker\_binary & \\
0 & 3,875 (94\%) \\
1 & 257 (6.2\%) \\
support & \\
Mean (SD) & 6.06 (1.03) \\
total\_siblings\_factor & \\
0 & 219 (5.3\%) \\
1 & 956 (23\%) \\
2 & 1,166 (28\%) \\
3 & 813 (20\%) \\
4 & 439 (11\%) \\
5 & 237 (5.7\%) \\
6 & 101 (2.4\%) \\
7 & 201 (4.9\%) \\
urban & \\
0 & 648 (16\%) \\
1 & 3,484 (84\%) \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Table~\ref{tbl-baseline-table-dogs} presents baseline data for the Study
w: the causal effects of dog ownership on multi-dimensional well-being.
The ``only\_dogs'' variable indicates the percentage of participants who
had or did not have cats at baseline. Baseline variables were included
to limit confounding of the the treatment/outcome effect.

\subsection{Appendix B. Measures}\label{appendix-b.-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' age in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Disability (waves: 5-15)}\label{disability-waves-5-15}

We assessed disability with a one item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}), that asks ``Do you have a health
condition or disability that limits you, and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

Participants were asked ``What is your highest level of
qualification?''. We coded participans highest finished degree according
to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG
codes (with overseas school quals coded as Level 3, and all other
ancillary categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{European (waves: 1-15)}\label{european-waves-1-15}

Participants were asked ``Which ethnic group do you belong to (NZ census
question)?'' or ``Which ethnic group(s) do you belong to? (Open-ended)''
(wave: 3). Europeans were coded as 1, whereas other ethnicities were
coded as 0.

\paragraph{Ethnicity (waves: 3)}\label{ethnicity-waves-3}

Based on the New Zealand Cencus, we asked participants ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020a}). (or 0.5
= neither female nor male)

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stablise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Number of Children (waves: 1-3,
4-15)}\label{number-of-children-waves-1-3-4-15}

We measured number of children using one item from Bulbulia
(\citeproc{ref-Bulbulia_2015}{2015}). We asked participants ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ````How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Political Orientation}\label{political-orientation}

We measured participants' political orientation using a single item
adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{NZSEI-13 (waves: 8-15)}\label{nzsei-13-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate an score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

Participants were asked ``If you are a parent, what is the birth date of
your eldest child?''.

\paragraph{Living with Partner}\label{living-with-partner}

Participants were asekd ``Do you live with your partner?'' (1 = Yes, 0 =
No).

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants personality with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}) which consists of six dimensions and each
dimensions is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I ften forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\subsubsection{Exposure variable}\label{exposure-variable}

Pets descriptoion here.

\subsubsection{Health well-being
outcomes}\label{health-well-being-outcomes}

\paragraph{Alcohol Frequency (waves:
6-15)}\label{alcohol-frequency-waves-6-15}

We measured participants' frequency of drinking alcohol using one item
adapted from Health (\citeproc{ref-Ministry_of_Health_2013}{2013}) .
Participants were asked ``How often do you have a drink containing
alcohol?'' (1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4
times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 =
Don't know).

\paragraph{Alcohol Intensity (waves:
6-15)}\label{alcohol-intensity-waves-6-15}

We measured participants' intensity of drinking alcohol using one item
adapted from (\citeproc{ref-Ministry_of_Health_2013}{Health 2013}).
Participants were asked ``How many drinks containing alcohol do you have
on a typical day when drinking alcohol? (number of drinks on a typical
day when drinking)''

\paragraph{Body Mass Index (waves: 2-3,
4-15)}\label{body-mass-index-waves-2-3-4-15}

Participants were asked ``What is your height? (metres)'' and ``What is
your weight? (kg)''. Based on participants indication of their height
and weight we calculated the BMI by dividing the weight in kilograms by
the square of the height in meters.

\paragraph{Short-Form Subjective Health (waves:
5-15)}\label{short-form-subjective-health-waves-5-15}

Participants' subjective health was assessed by three items selected
from the MOS 36-item short-form health survey
(\citeproc{ref-warejr1992}{Ware Jr and Sherbourne 1992}). The items were

\begin{verbatim}
1.  "In general, would you say your health is...";
2.  "I seem to get sick a little easier than most people.";
3.  "I expect my health to get worse." Participants responded to those items on a scale (1 = Poor to 7 = Excellent).
\end{verbatim}

The second and third items were negatively-worded, so we reversed the
responses.

\paragraph{Hours of Exercise (waves: 1,
4-15)}\label{hours-of-exercise-waves-1-4-15}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}). We asked participants to estimate and
report how many hours they spend in exercise/physical activity last
week. To stablise this indicator, we first took the natural log of the
response + 1, and then centred and standardised the log-transformed
indicator.

\paragraph{Hours of Sleep (waves:
5-15)}\label{hours-of-sleep-waves-5-15}

Participants were asked ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night''.

\paragraph{Smoker (waves: 4-15)}\label{smoker-waves-4-15}

We asked participants whether they are currently smoking or not (1 = Yes
or 0 = No), using a single item: ``Do you currently smoke?'' or ``Do you
currently smoke tobacco cigarettes?'' (waves: 10-15) from Muriwai
\emph{et al.} (\citeproc{ref-muriwai_looking_2018}{2018}).

\subsubsection{Embodied well-being
outcomes}\label{embodied-well-being-outcomes}

\paragraph{Kessler-6 (waves: 2-3,4-15)}\label{kessler-6-waves-2-34-15}

We measured psychological distress using the Kessler-6 scale
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002}), which exhibits
strong diagnostic concordance for moderate and severe psychological
distress in large, cross-cultural samples
(\citeproc{ref-kessler2010}{Kessler \emph{et al.} 2010};
\citeproc{ref-prochaska2012}{Prochaska \emph{et al.} 2012}).
Participants rated during the past 30 days, how often did\ldots{} (

\begin{verbatim}
1.  "... you feel hopeless";
2.  "... you feel so depressed that nothing could cheer you up";
3.  "... you feel restless or fidgety";
4.  "... you feel that everything was an effort";
5.  "... you feel worthless";
6.  " you feel nervous?"
\end{verbatim}

Ordinal response options for the Kessler-6 are: ``None of the time'';
``A little of the time''; ``Some of the time''; ``Most of the time'';
``All of the time.''

\paragraph{Fatigue (waves: 5-15)}\label{fatigue-waves-5-15}

We assessed subjective fatigue by asking participants, ``During the last
30 days, how often did \ldots{} you feel exhausted?'' Responses were
collected on an ordinal scale (0 = None of The Time, 1 = A little of The
Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

\paragraph{Rumination}\label{rumination}

``During the last 30 days, how often did\ldots. you have negative
thoughts that repeated over and over?''

Ordinal response options for the Kessler-6 are: ``None of the time'';
``A little of the time''; ``Some of the time''; ``Most of the time'';
``All of the time.''

\subsubsection{Reflective well-being}\label{reflective-well-being}

\paragraph{Satisfaction with Life (waves:
1-3,4-15)}\label{satisfaction-with-life-waves-1-34-15}

We measured life satisfaction with two items adapted from the
Satisfaction with Life Scale (\citeproc{ref-diener1985}{Diener \emph{et
al.} 1985}):

\begin{verbatim}
1.  "I am satisfied with my life" and
2.  "In most ways my life is close to ideal".
\end{verbatim}

Participants responded on a scale from 1 (Strongly Disagree) to 7
(Strongly Agree).

\paragraph{Personal Wellbeing (waves: 1-3,
4-15)}\label{personal-wellbeing-waves-1-3-4-15}

We measured participants' subjective wellbeing using three items from
the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003}):

\begin{verbatim}
1.  Your health;
2.  Your standard of living;
3.  Your future security; 4 Your personal relationships.
\end{verbatim}

Participants read an instruction (``The following items assess your
current satisfaction with different aspects of your life and aspects of
New Zealand more generally'') and indicated their satisfaction with
those items (0 = Completely Dissatisfied to 10 = Completely Satisfied).

\paragraph{Standard Living}\label{standard-living}

We measured participants' satisfaction with their standard of living
using an item from the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003}).
Participants read an instruction (``Please rate your level of
satisfaction with the following aspects of your life and New Zealand.'')
and responded to an item

\begin{verbatim}
- "Your standard of living"
\end{verbatim}

on a 10-point scale (0 = completely dissatisfied to 10 = completely
satisfied).

\subsubsection{Social well-being
outcomes}\label{social-well-being-outcomes}

\paragraph{Felt Belongingness (waves: 1-3,
4-15)}\label{felt-belongingness-waves-1-3-4-15}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (\citeproc{ref-hagerty1995}{Hagerty and Patusky
1995}):

\begin{verbatim}
1.  "Know that people in my life accept and value me";
2.  "Feel like an outsider";
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  ``Know that people around me share my attitudes and beliefs''.
\end{enumerate}

Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very
Accurate). The second item was reversely coded.

\paragraph{Sense of Community (waves:
6-15)}\label{sense-of-community-waves-6-15}

We measured sense of community with a single item from Sengupta \emph{et
al.} (\citeproc{ref-sengupta2013}{2013}): ``I feel a sense of community
with others in my local neighbourhood.'' Participants answered on a
scale of 1 (strongly disagree) to 7 (strongly agree).

\paragraph{Support (waves: 1-3, 4-15)}\label{support-waves-1-3-4-15}

Participants' perceived social support was measured using three items
from Cutrona and Russell (\citeproc{ref-cutrona1987}{1987}) and Williams
\emph{et al.} (\citeproc{ref-williams_cyberostracism_2000}{2000}):

\begin{verbatim}
1.  "There are people I can depend on to help me if I really need it";
2.  "There is no one I can turn to for guidance in times of stress";
3.  "I know there are people I can turn to when I need help." 
\end{verbatim}

Participants indicated the extent to which they agree with those items
(1 = Strongly Disagree to 7 = Strongly Agree).

The second item was negatively-worded, so we reversely recorded the
responses to this item.

\newpage{}

\subsubsection{Appendix C. Comparison of Shift Estimand with Traditional
Causal
Contrast}\label{appendix-c.-comparison-of-shift-estimand-with-traditional-causal-contrast}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-comparative-graph-cats-1.pdf}

}

\caption{\label{fig-comparative-graph-cats}A comparison of the classical
causal estimand with the shift estimand employed in this study: cats and
sleep}

\end{figure}%

\newpage{}

\begin{table}

\caption{\label{tbl-comparative-graph-cats}A comparison of the classical
causal estimand with the shift estimand employed in this study: cats and
sleep}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4157}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1798}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0899}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0899}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0899}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1348}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Hours sleep (SD): shift estimand & -0.0573 & -0.0963 & -0.0183 & 1.2910
& 1.1478 \\
Hours sleep (SD): trational estimand & -0.0833 & -0.1431 & -0.0236 &
1.3702 & 1.1708 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

\newpage{}

Here, we consider two distinct types of estimands: the shift estimand
and the traditional all-or-nothing estimand. The shift estimand aims to
quantify the change in expected well-being when individuals transition
from non-ownership to pet ownership, set against the current
distribution of pet owners and non-owners in the population. In
contrast, the traditional all-or-nothing estimand compares expected
well-being under conditions of universal pet ownership versus no pet
ownership at all.

n Study 1, we observed an effect of cat ownership on sleep. For
comparative insights, one may ask: What would the traditional estimand
reveal? Refer to \textbf{?@fig-comparative-graph-cat} and
Table~\ref{tbl-comparative-graph-cats}. These show that the traditional
estimand, although less precise, reveals the traditional intervention
would have stronger effects than the shift estimand. This is expected
given the traditional estimand requires a more substantial intervention
and greater data dependency for exposure balance.

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-fl-pets_files/figure-pdf/fig-comparative-graph-dogs-1.pdf}

}

\caption{\label{fig-comparative-graph-dogs}A comparison of the classical
causal estimand with the shift estimand employed in this study: dogs and
exercise}

\end{figure}%

\begin{table}

\caption{\label{tbl-comparative-graph-dogs}A comparison of the classical
causal estimand with the shift estimand employed in this study: dogs and
exercise}

\centering{

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4624}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1720}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0753}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0753}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0860}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1290}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Hours excercise (SD): shift estimand & 0.0742 & 0.0068 & 0.1417 & 1.3432
& 1.0860 \\
Hours excercise (SD): traditional estimand & 0.0979 & 0.0130 & 0.1828 &
1.4123 & 1.1227 \\
\end{longtable}

\addtocounter{table}{-1}

}

\end{table}%

Study 2 examined a effect of dog ownership on exercise across the
population were everyone to own dogs. The contrast condition for this
intervention was the natural distribution of dog ownership in the
population. Again, we might wonder: What insights would the traditional
estimand offer? See Figure~\ref{fig-comparative-graph-dogs} and
Table~\ref{tbl-comparative-graph-dogs} for a comparative analysis.
Similar to the cat study, the traditional estimand yields stronger but
less precise results, owing to a more extensive intervention and higher
data requirements for balance.

It is important to recognise that each estimand poses a different
research question, leading to distinct intervention implications. The
shift estimand yields more conservative results, aligning with current
pet ownership behaviours. Beyond increased efficiency and fewer
assumptions, the shift estimand has the advantage of a potentially more
immediate policy relevance. The insights it offers could guide policy
makers interested in promoting pet ownership without necessarily
discouraging current pet owners.

\newpage{}

\subsubsection{Appendix D. Population Average Treatment
Effect}\label{appendix-d.-population-average-treatment-effect}

As indicated in the main manuscript, the Average Treatment Effects is
obtained by contrasting the expected outcome when a population sampled
is exposed to an exposure level, \(E[Y(A = a)]\), with the expected
outcome under a different exposure level, \(E[Y(A=a')]\).

For a binary treatment with levels \(A=0\) and \(A=1\), the Average
Treatment Effect (ATE), on the difference scale, is expressed:

\[ATE_{\text{risk difference}} = E[Y(1)|L] - E[Y(0)|L]\]

On the risk ratio scale, the ATE is expressed:

\[ATE_{\text{risk ratio}} = \frac{E[Y(1)|L]}{E[Y(0)|L]}\]

Other effect scales, such as the incidence rate ratio, incidence rate
difference, or hazard ratio, might also be of interest.

Here we estimate the Population Average Treatment Effect (PATE), which
denotes the effect the treatment would have on the New Population if
applied universally. This quantity can be expressed:

\[PATE_{\text{risk difference}} = f(E[Y(1) - Y(0)|L], W)\]

\[PATE_{\text{risk ratio}} = f\left(\frac{E[Y(1)|L]}{E[Y(0)|L]}, W\right)\]

where \(f\) is a function that incorporates post-stratification weights
\(W\) into the estimation of the expected outcomes from which we obtain
causal contrasts. Because the NZAVS is national probability sample,
i.e.~inverse probability of being sampled 1. However, to incorporate
gender, age, and ethnic differences we include post-stratification
weight into our outcome wide models.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, S, J. A. (2015) Religion and parental cooperation: An
empirical test of slone's sexual signaling model. In \&. V. S. J. Slone
D., ed., \emph{The attraction of religion: A sexual selectionist
account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-cummins_developing_2003}
Cummins, RA, Eckersley, R, Pallant, J, Vugt, J van, and Misajon, R
(2003) Developing a national index of subjective wellbeing: The
australian unity wellbeing index. \emph{Social Indicators Research},
\textbf{64}(2), 159--190.
doi:\href{https://doi.org/10.1023/A:1024704320683}{10.1023/A:1024704320683}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diener1985}
Diener, E, Emmons, RA, Larsen, RJ, and Griffin, S (1985) The
Satisfaction With Life Scale. \emph{Journal of Personality Assessment},
\textbf{49}(1), 71--75.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020a)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-fraser2020}
Fraser, G, Huang, Y, Robinson, K, Wilson, MS, Bulbulia, J, and Sibley,
CG (2020b) New zealand pet owners{'} demographic characteristics,
personality, and health and wellbeing: More than just a fluff piece.
\emph{Anthrozoös}, \textbf{33}(4), 561578.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-Ministry_of_Health_2013}
Health, M of (2013) \emph{The new zealand health survey: Content guide
2012-2013}, Princeton University Press.

\bibitem[\citeproctext]{ref-hernan2023}
Hernan, MA, and Robins, JM (2023) \emph{Causal inference}, Taylor \&
Francis. Retrieved from
\url{https://books.google.co.nz/books?id=/_KnHIAAACAAJ}

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kessler2002}
Kessler, R~C, Andrews, G, Colpe, L~J, \ldots{} Zaslavsky, A~M (2002)
Short screening scales to monitor population prevalences and trends in
non-specific psychological distress. \emph{Psychological Medicine},
\textbf{32}(6), 959--976.
doi:\href{https://doi.org/10.1017/S0033291702006074}{10.1017/S0033291702006074}.

\bibitem[\citeproctext]{ref-kessler2010}
Kessler, RC, Green, JG, Gruber, MJ, \ldots{} Zaslavsky, AM (2010)
Screening for serious mental illness in the general population with the
K6 screening scale: results from the WHO World Mental Health (WMH)
survey initiative. \emph{International Journal of Methods in Psychiatric
Research}, \textbf{19}(S1), 4--22.
doi:\href{https://doi.org/10.1002/mpr.310}{10.1002/mpr.310}.

\bibitem[\citeproctext]{ref-muriwai_looking_2018}
Muriwai, E, Houkamau, CA, and Sibley, CG (2018) Looking like a smoker, a
smokescreen to racism? Māori perceived appearance linked to smoking
status. \emph{Ethnicity \& Health}, \textbf{23}(4), 353--366.
doi:\href{https://doi.org/10.1080/13557858.2016.1263288}{10.1080/13557858.2016.1263288}.

\bibitem[\citeproctext]{ref-polley2023}
Polley, E, LeDell, E, Kennedy, C, and Laan, M van der (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://CRAN.R-project.org/package=SuperLearner}

\bibitem[\citeproctext]{ref-prochaska2012}
Prochaska, JJ, Sung, H-Y, Max, W, Shi, Y, and Ong, M (2012) Validity
study of the K6 scale as a measure of moderate mental distress based on
mental health treatment need and utilization: The K6 as a measure of
moderate mental distress. \emph{International Journal of Methods in
Psychiatric Research}, \textbf{21}(2), 88--97.
doi:\href{https://doi.org/10.1002/mpr.1349}{10.1002/mpr.1349}.

\bibitem[\citeproctext]{ref-sengupta2013}
Sengupta, NK, Luyten, N, Greaves, LM, \ldots{} Sibley, CG (2013) Sense
of Community in New Zealand Neighbourhoods: A Multi-Level Model
Predicting Social Capital. \emph{New Zealand Journal of Psychology},
\textbf{42}(1), 36--45.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-warejr1992}
Ware Jr, JE, and Sherbourne, CD (1992) The MOS 36-item short-form health
survey (SF-36): I. Conceptual framework and item selection.
\emph{Medical Care}, 473483.

\bibitem[\citeproctext]{ref-williams_cyberostracism_2000}
Williams, KD, Cheung, CKT, and Choi, W (2000) Cyberostracism: Effects of
being ignored over the internet. \emph{Journal of Personality and Social
Psychology}, \textbf{79}(5), 748--762.
doi:\href{https://doi.org/10.1037/0022-3514.79.5.748}{10.1037/0022-3514.79.5.748}.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}



\end{document}
