---
title: "Measurement for Cross-Cultural Research"
author: 
  - name: Joseph A. Bulbulia
    affiliation: Victoria University of Wellington, New Zealand
    orcid_id: 0000-0002-5861-2056
    email: joseph.bulbulia@vuw.ac.nz
    corresponding: yes
execute:
  warning: false
  eval: true
  echo: false
  include: true
html:
   html-math-method: katex
---

```{r}
#| label: load-libraries
#| echo: false
#| include: false
#| eval: false

#   html:
#    html-math-method: katex

# Include in YAML for Latex
# sanitize: true
# keep-tex: true
# include-in-header:
#       - text: |
#           \usepackage{cancel}


# for making graphs
library("tinytex")
library(extrafont)
loadfonts(device = "all")


# libraries for jb (when internet is not accessible)
# read libraries
source("/Users/joseph/GIT/templates/functions/libs2.R")

# read functions
source("/Users/joseph/GIT/templates/functions/funs.R")

# read data/ set to path in your computer
pull_path <-
  fs::path_expand(
    "/Users/joseph/v-project\ Dropbox/data/current/nzavs_13_arrow"
  )

# for saving models. # set path fo your computer
push_mods <-
  fs::path_expand(
    "/Users/joseph/v-project\ Dropbox/data/nzvs_mods/00drafts/23-causal-dags"
  )
```

## Abstract

## Introduction


### Review:

#### **State the population for whom the causal question applies**

We need to define for whom our causal inference applies. For this purpose, it is useful to distinguish the concepts of source and target population, and between the concepts of generalisability and transportability.

The **source population** is the population from whom our sample is drawn. The **target population** is the larger group for which we aim to apply our study's results. The closer the source matches the target in ways that are relevant to our causal questions, the stronger our causal inferences about the target population will be.

**Generalisability** refers to the ability to apply the causal effects estimated from a sample to the source population. In simpler terms, it deals with the extrapolation of causal knowledge from a sample to the broader population. This concept is also called "external validity."

$$\text{Generalisability} = PATE \approx ATE_{\text{sample}}$$

Where the $PATE$ is a population average treatment effect. Although beyond the scope of this study, we may use post-stratification weights to obtain the PATE such that

$$PATE =  f(ATE_{\text{source}}, W)$$

where $f(.,W)$ denotes a survey weighting function.

**Transportability** refers to the ability to extrapolate causal effects learned from a source population to a target population when certain conditions are met. It pertains to the transfer of causal knowledge across different settings or populations.

$$\text{Transportability} = ATE_{\text{target}} \approx f(ATE_{\text{source}}, T)$$

where $f$ is a function and $T$ is a function that maps the results from our source population to another population. To achieve transportability, we need information about the source and target populations and an understanding of how the relationships between treatment, outcome, and covariates differ between the populations. Assessing transportability requires additional data or specialist knowledge. For example whether the causal effects for the effect of religious service attendance in one culture at one time transport to same culture at another time, or to another culture, cannot be determined *a priori*.

### Types of measurement error

#### 1. **Uncorrelated non-differential (undirected) measurement error**

As shown in @fig-dag-uu-null, uncorrelated non-differential measurement error occurs when the errors in measurement of the exposure and outcome are not related to each other or to the level of exposure or outcome. For example, imagine that some ancient societies randomly omitted or added details about 'beliefs in Big Gods' and 'social complexity' in their records, or that the records were not preserved equally across cultures for reasons unrelated to these parameters. In this case, errors in the documentation of both variables are random and not related to the intensity of the beliefs in Big Gods or the level of social complexity. Here we would have an instance of uncorrelated and non-differential error.

Uncorrelated non-differential measurement error does not create bias under the null. As evident from @fig-dag-uu-null, d-separation is preserved. However, if there were a true effect of the exposure on the outcome, non-differential measurement error in both the exposure and the outcome would lead to an attenuation of the true effect estimate. This phenomenon is sometimes referred to as "regression dilution bias" or "attenuation bias". This scenario is presented in @fig-dag-uu-null. The presence of uncorrelated undirected measurement error in the exposure and outcome variables can lead to attenuation bias because the effect size is underestimated due to the 'noise' introduced by these errors. Depending on one's loss function, failing to detect true effects may be more harmful than bias away from the null. For this reason, uncorrelated non-differential measurement error can be problematic even though it does not induce bias away from the null.

```{tikz}
#| label: fig-dag-uu-null
#| fig-cap: "Uncorrelated non-differential measurement error does not bias estimates under the null."
#| out-width: 60%
#| echo: false
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}



\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=white] (UA) at (0, 1) {U$_A$};
\node [rectangle, draw=white] (UY) at (0, 2) {U$_Y$};

\node [rectangle, draw=black] (A1) at (2, 1) {$A^{t1}$};
\node [rectangle, draw=black] (Y2) at (4, 1) {$Y^{t2}$};
\node [rectangle, draw=white] (Aeta1) at (2, 0) {$\eta^{t1}_A$};
\node [rectangle, draw=white] (Yeta2) at (4, 0) {$\eta^{t2}_Y$};


\draw [-latex, draw=black] (UA) to (A1);
\draw [-latex, draw=black,bend left=10] (UY) to (Y2);
\draw [-latex, draw=black] (Aeta1) to (A1);
\draw [-latex, draw=black] (Yeta2) to (Y2);

\end{tikzpicture}
```

#### 2. **Uncorrelated differential (or directed) measurement error**

As shown in \@ fig-dag-indep-d-effect, uncorrelated differential (or directed) measurement error occurs when the errors in measurement are related to the level of exposure or outcome, but not to each other. For instance, societies with stronger 'beliefs in Big Gods' might provide more detailed accounts of their religious beliefs, but the quality or extent of their records on 'social complexity' might not be affected by their religious beliefs or vice versa. Here, the errors are differential as they depend on the intensity of religious beliefs, but uncorrelated as the errors in documenting 'beliefs in Big Gods' and 'social complexity' are independent of each other. Uncorrelated differential (or directed) measurement error is presented in @fig-dag-indep-d-effect and leads to bias under the null. The bias preented in @fig-directed-measurement-error is an example of directed measurement error from panel attrition in which the true exposure and the true outcome affect selection.

```{tikz}
#| label: fig-dag-indep-d-effect
#| fig-cap: "Directed independent (uncorrelated) measurement error biases effect estimates. The selection bias presented in the previous graph is an instance of directed independent measurement error."
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations.markings}

\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

% Define a simple decoration
\tikzstyle{cor} = [-, dotted, preaction = {decorate}]

\begin{tikzpicture}[every node/.append style={draw}]
\node [rectangle, draw=white] (UA) at (0, 0) {U$_A$};

\node [rectangle, draw=black] (A1) at (2, 0) {$A^{t1}$};
\node [rectangle, draw=white] (UY) at (4, 0) {U$_Y$};

\node [rectangle, draw=black] (Y2) at (6, 0) {$Y^{t2}$};
\node [rectangle, draw=white] (Aeta1) at (2, -1) {$\eta^{t1}_A$};
\node [rectangle, draw=white] (Yeta2) at (6, -1) {$\eta^{t2}_Y$};


\draw [-latex, draw=black] (UA) to (A1);
\draw [-latex, draw=red] (UY) to (Y2);
\draw [-latex, draw=red] (Aeta1) to (UY);
\draw [-latex, draw=black] (Aeta1) to (A1);
\draw [-latex, draw=black] (Yeta2) to (Y2);
\draw [cor, draw=black, dotted, bend left] (Aeta1) to (UA);


\end{tikzpicture}
```

#### 3. **Correlated non-differential (undirected) measurement error**

As shown @fig-dag-dep-u-effect correlated non-differential (undirected) measurement error occurs when the errors in measuring both exposure and outcome are related to each other, but not to the level of exposure or outcome. The scenario is presented in @fig-dag-d-d. Imagine that some societies had more advanced record-keeping systems that resulted in more accurate and detailed accounts of both 'beliefs in Big Gods' and 'social complexity'. These errors might be correlated because the accuracy of records on both variables is influenced by the same underlying factor (the record-keeping abilities), but they are non-differential as they do not depend on the intensity of religious beliefs or the level of social complexity. Correlated non-differential measurement error may induce bias under the null.

```{tikz}
#| label: fig-dag-dep-u-effect
#| fig-cap: "Correlated undirected measurement error can dilute the estimates of true effects"
#| out-width: 80%
#| echo: false
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations.markings}

\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

% Define a simple decoration
\tikzstyle{cor} = [-, dotted, preaction = {decorate}]

\begin{tikzpicture}[every node/.append style={draw}]

\node [rectangle, draw=white] (UAY) at (0, 2) {U$_{AY}$};
\node [rectangle, draw=white] (UA) at (2, 1) {U$_A$};
\node [rectangle, draw=white] (UY) at (2, 3) {U$_Y$};

\node [rectangle, draw=black] (A1) at (4, 1) {A$^{t1}$};
\node [rectangle, draw=black] (Y2) at (6, 1) {Y$^{t2}$};
\node [rectangle, draw=white] (Aeta1) at (4, 0) {$\eta^{t1}_A$};
\node [rectangle, draw=white] (Yeta2) at (6, 0) {$\eta^{t2}_Y$};



\draw [-latex, draw=red] (UAY) to (UA);
\draw [-latex, draw=red] (UAY) to (UY);
\draw [-latex, draw=black] (UA) to (A1);
\draw [-latex, draw=red, bend left=30] (UY) to (Y2);
\draw [-latex, draw=black] (Aeta1) to (A1);
\draw [-latex, draw=black] (Yeta2) to (Y2);
\draw [cor, draw=red, bend left] (Aeta1) to (UA);

\end{tikzpicture}

```

#### 4. **Correlated differential (directed) measurement error**

As presented in @fig-dag-d-d, correlated differential (directed) measurement error occurs when the errors in measurement are related to each other and also to the level of exposure or outcome. Suppose that societies with stronger beliefs in Big Gods tend to have more detailed records about their religious beliefs and social structure, possibly because a highly organized religion encourages elaborate documentation or monumental architecture. In this case, the errors are differential because societies with stronger beliefs in Big Gods have less error in their documentation, and correlated because the same factor (strength of religious beliefs) influences the errors in both 'beliefs in Big Gods' and 'social complexity'.

```{tikz}
#| label: fig-dag-d-d
#| fig-cap: "Directed dependent (correlated) measurement error biases effect estimates. Here, the exposure affects the measurement error of the outcome. Additionally, the measurement errors of the exposure and outcome are correlated. These dynamics open pathways for bias. "
#| out-width: 100%
#| echo: false


\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations.markings}

\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

% Define a simple decoration
\tikzstyle{cor} = [-, dotted, preaction = {decorate}]

\begin{tikzpicture}[every node/.append style={draw}]
\node [rectangle, draw=white] (UAY) at (0, 0) {U$_{AY}$};
\node [rectangle, draw=white] (UA) at (2, 0) {U$_A$};

\node [rectangle, draw=black] (A1) at (4, 0) {$A^{t1}$};
\node [rectangle, draw=white] (UY) at (6, 0) {$U_Y$};

\node [rectangle, draw=black] (Y2) at (8, 0) {$Y^{t2}$};
\node [rectangle, draw=white] (Aeta1) at (4, -1) {$\eta^{t1}_A$};
\node [rectangle, draw=white] (Yeta2) at (8, -1) {$\eta^{t2}_Y$};


\draw [-latex, draw=red] (UAY) to (UA);
\draw [-latex, draw=red, bend left] (UAY) to (UY);
\draw [-latex, draw=black] (UA) to (A1);
\draw [-latex, draw=red] (UY) to (Y2);
\draw [-latex, draw=red] (Aeta1) to (UY);
\draw [-latex, draw=black] (Aeta1) to (A1);
\draw [-latex, draw=black] (Yeta2) to (Y2);
\draw [cor, draw=red, dashed] (Aeta1) to (UA);
\end{tikzpicture}
```

### Comparative research viewed as correlated undirected measurment error

Against invariance testing, we should approach comparative research from the vantage point of correlated measurement error. Amending @fig-dag-dep-u-effect. Selecting on unmeasured correlated error structures in the world we have @fig-dag-dep-u-effect-selection.   Were we to select from a setting in which there was no systematic (correlated) error structures between the measurements of the exposures and the measurements of the outcomes we would avoid such confounding. 

Note that it is not merely a matter of transporting results from the sample population to another population. Rather, the act of selection induces bias. 

```{tikz}
#| label: fig-dag-dep-u-effect-selection
#| fig-cap: "Measurement bias in comparative cross-cultural research"
#| out-width: 100%
#| echo: false
#| 
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations.markings}

\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

% Define a simple decoration
\tikzstyle{cor} = [-, dotted, preaction = {decorate}]

\begin{tikzpicture}[every node/.append style={draw}]

\node [rectangle, draw=black] (S) at (0, 2) {S};
\node [rectangle, draw=white] (UAY) at (2, 2) {U$_{AY}$};
\node [rectangle, draw=white] (UA) at (4, 1) {U$_A$};
\node [rectangle, draw=white] (UY) at (4, 3) {U$_Y$};

\node [rectangle, draw=black] (A1) at (6, 1) {A$^{t1}$};
\node [rectangle, draw=black] (Y2) at (8, 1) {Y$^{t2}$};
\node [rectangle, draw=white] (Aeta1) at (6, 0) {$\eta^{t1}_A$};;
\node [rectangle, draw=white] (Yeta2) at (8, 0) {$\eta^{t2}_Y$};


\draw [-latex, draw=red] (UAY) to (UA);
\draw [-latex, draw=red] (UAY) to (UY);
\draw [-latex, draw=black] (UA) to (A1);
\draw [-latex, draw=red, bend left=30] (UY) to (Y2);
\draw [-latex, draw=black] (Aeta1) to (A1);
\draw [-latex, draw=black] (Yeta2) to (Y2);
\draw [cor, draw=red, bend left] (Aeta1) to (UA);
\draw [-latex, draw=black] (S) to (UAY);

\end{tikzpicture}

```

##  Review of the theory of multiple versions of treatment

```{tikz}
#| label: fig_dag_multiple_version_treatment_dag
#| fig-cap: "Multiple Versions of treatment. Heae, A is regarded to bbe a coarseneed version of K"
#| out-width: 100%
#| echo: false


\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}



\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=black] (L0) at (0, 0) {L};
\node [rectangle, draw=white] (K1) at (2, 0) {K};
\node [rectangle, draw=black] (A1) at (4, 0) {A};
\node [rectangle, draw=white] (Y2) at (6, 0) {Y$_k$};

\draw [-latex, draw=black] (L0) to (K1);
\draw [-latex, bend right, draw=black] (L0) to (Y2);
\draw [-latex, draw=black] (K1) to (A1);
\draw [-latex, draw=black, bend left] (K1) to (Y2);

\end{tikzpicture}
```


Recall, a causal effect is defined as the difference in the expected potential outcome when everyone is exposed (perhaps contrary to fact) to one level of a treatment, conditional on their levels of a confounder, with the expected potential outcome when everyone is exposed to a a different level of a treatement (perhaps contrary to fact), conditional on their levels of a counfounder.

$$ \delta = \sum_l \left( \mathbb{E}[Y|A=a,l] - \mathbb{E}[Y|A=a^*,l] \right) P(l)$$

where $\delta$ is the causal estimand on the difference scale $(\mathbb{E}[Y^0 - Y^0])$.

In causal inference, the multiple versions of treatment theory allows us to handle situations where the treatment isn not uniform, but instead has several variations. Each variation or "version" of the treatment can have a different effect on the outcome. However, consistency is not violated because it is redefined: for each version of the treatment, the outcome under that version is equal to the observed outcome when that version is received. Put differently we may think of the indicator $A$ as corresponding to many version of the true treament $K$. Where conditional independence holds such that there is a absence of confounding for the effect of $K$ on $Y$ given $L$, we have: $Y(k)\coprod A|K,L$. This states conditional on $L$, $A$ gives no information about $Y$ once $K$ and $L$ are accounted for. When $Y = Y(k)$ if $K = k$ and Y$(k)$ is independent of $K$, condition on $L$, then $A$ may be thought of as a coarsened indicator of $K$, as shown in @fig_dag_multiple_version_treatment_dag. We may estimate consistent causal effects where:

$$ \delta = \sum_{k,l} \mathbb{E}[Y(k)|l] P(k|a,l) P(l) - \sum_{k,l} \mathbb{E}[Y(k)|l] P(k|a^*,l) P(l)$$

The scenario represents a hypothetical randomised trial where within strata of covariates $L$, individuals in one group receive a treatment $K$ version randomly assigned from the distribution of $K$ distribution $(A = 1, L = l)$ sub-population. Meanwhile, individuals in the other group receive a randomly assigned $K$ version from $(A = 0, L = l)$

This theory finds its utility in practical scenarios where treatments seldom resemble each other (see: [@vanderweele2013]).

### Reflective and formative measurement models may be approached as multiple versions of treatment

Vanderweele applies the following substitution:

$$\delta = \sum_{\eta,l} \mathbb{E}[Y_\eta|l] P(\eta|A=a+1,l) P(l) - \sum_{\eta,l} \mathbb{E}[Y_\eta|l] P(\eta|A=a,l) P(l)$$

Specifically, we substitue $K$ with $\eta$ from the previous section, and compare the measurement response $A = a + 1$ with $A = a$. We discover that if the influence of $\eta$ on $Y$ is not confounded given $L$, then the multiple versions of reality consistent with the reflective and formative statistical models of reality will not lead to biased estimation. $\delta$ retains its interpretability as a comparison in a hypothetical randomised trial in which the distribution of coarsened measures of $\eta_A$ are balanced within levels of the treatment, conditional on $\eta_L$.

This connection between measurement and the multiple versions of treatment framework provides a hope for consistent causal inference varying reliabilities of measurement.

However, as with the theory of multiple treatments, we might not known how to interpret our results because we don't know the true relationships between our measured indicators and underlying reality.

How can we do better?

```{tikz}
#| label: fig-dag-multiple-version-treatment-applied-measurement
#| fig-cap: "Multiple Versions of treatment applied to measuremen.Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false


\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}



\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=black] (L0) at (0, 0) {L};
\node [rectangle, draw=white] (K1) at (2, 0) {$\eta$=K};
\node [rectangle, draw=white] (X1) at (5, 0) {$(X_1, X_2, \dots X_n)$};
\node [rectangle, draw=black] (A1) at (8, 0) {A};
\node [rectangle, draw=white] (Y2) at (10, 0) {Y$_k$};

\draw [-latex, draw=black] (L0) to (K1);
\draw [-latex, bend right, draw=black] (L0) to (Y2);
\draw [-latex, draw=black] (K1) to (X1);
\draw [-latex, draw=black] (X1) to (A1);
%\draw [-latex, draw=white, bend left] (K1) to (Y2); # fix later

\end{tikzpicture}
```

## Measurement and psychometric research.

In psychometric research, formative and reflective models describe the relationship between latent variables and their respective indicators.

### Reflective Model (Factor Analysis)

In a reflective measurement model, also known as an effect indicator model, the latent variable is understood to cause the observed variables. In this model, changes in the latent variable cause changes in the observed variables. Each indicator (observed variable) is a 'reflection' of the latent variable. In other words, they are effects or manifestations of the latent variable. These relations are presented in @fig-dag-latent-1.

The reflective model may be expressed:

$$X_i = \lambda_i \eta + \varepsilon_i$$

Here, $X_i$ is an observed variable (indicator), $\lambda_i$ is the factor loading for $X_i$, $\eta$ is the latent variable, and $\varepsilon_i$ is the error term associated with $X_i$. It is assumed that all the indicators are interchangeable and have a common cause, which is the latent variable $\eta$.

In the conventional approach of factor analysis, the assumption is that a common latent variable is responsible for the correlation seen among the indicators. Thus, any fluctuation in the latent variable should immediately lead to similar changes in the indicators.These assumptions are presented in @fig-dag-latent-1.

```{tikz}
#| label: fig-dag-latent-1
#| fig-cap: "Reflective model: assume univariate latent variable η giving rise to indicators X1...X3. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 80%
#| echo: false
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}



\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=white] (eta) at (0, 0) {$\eta$};
\node [rectangle, draw=white] (X1) at (6, 1) {X$_1$};
\node [rectangle, draw=white] (X2) at (6, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (6, -1) {X$_n$};

\draw [-latex, draw=black] (eta) to (X1);
\draw [-latex, draw=black] (eta) to (X2);
\draw [-latex, draw=black] (eta) to (Xn);

\end{tikzpicture}
```

### The Formative Model (Factor Analysis)

In a formative measurement model, the observed variables are seen as causing or determining the latent variable. Here again, there is a single latent variable. However this latent variable is taken to be an effect of the underlying indicators. These relations are presented in @fig-dag-latent-formative_0.

The formative model may be expressed:

$$\eta = \sum_i\lambda_i X_i + \varepsilon$$

In this equation, $\eta$ is the latent variable, $\lambda_i$ is the weight for $X_i$ (the observed variable), and $\varepsilon$ is the error term. The latent variable $\eta$ is a composite of the observed variables $X_i$.

In the context of a formative model, correlation or interchangeability between indicators is not required. Each indicator contributes distinctively to the latent variable. As such, a modification in one indicator doesn't automatically imply a corresponding change in the other indicators.

```{tikz}
#| label: fig-dag-latent-formative_0
#| fig-cap: "Formative model:: assume univariate latent variable from which the indicators X1...X3 give rise. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 80%
#| echo: false
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}



\begin{tikzpicture}[{every node/.append style}=draw]

\node [rectangle, draw=black] (X1) at (0, 1) {X1};
\node [rectangle, draw=white] (X2) at (0, 0) {$\vdots$};
\node [rectangle, draw=black] (Xn) at (0, -1) {X$_n$};
\node [rectangle, draw=white] (eta) at (6, 0) {$\eta$};


\draw [-latex, draw=black] (X1) to (eta);
\draw [-latex, draw=black] (X2) to (eta);
\draw [-latex, draw=black] (Xn) to (eta);

\end{tikzpicture}
```

## Structural Interpretation of the formative model and reflective models (Factor Analysis)

VanderWeele has recently raised a host of problems arising for formative and reflective models that become clear when we examine their causal assuptions [@vanderweele2022].

> However, this analysis of reflective and formative models assumed that the latent η was causally efficacious. This may not be the case (VanderWeele 2022)

VanderWeele distinguishes between statistical and structural interpretations of the equations preesented above.

1.  **Statistical Model:** a mathematical construct that shows how observable variables, also known as indicators, are related to latent or unseen variables. These are presented in the equations above

2.  **Structural Model:** A structural model refers to the causal assumptions or hypotheses about the relationships among variables in a statistical model. The assumptions of the factor analytic tradition are presented in @fig-dag-latent-formative_0 and @fig-dag-latent-1 are structural models.

We have seen that the **reflective model** statistically implies that the observed variables (indicators) are reflections or manifestations of the latent variable, expressed as $X_i = \lambda_i \eta + \varepsilon_i$. However, the factor analytic tradition makes the additional structural assumption that a univariate latent variable is causally efficacious and influences the observed variables, as in: @fig-structural-assumptions-reflective-model.

We have also seen that the **formative model** statistically implies that the latent variable is formed or influenced by the observed variables, expressed as $\eta = \sum_i\lambda_i X_i + \varepsilon$. However, the factor analytic tradition makes the additional assumption that the observed variables give rise to a univariate latent variable, as in @fig-dag-reflective-assumptions_note.

```{tikz}
#| label: fig-structural-assumptions-reflective-model
#| fig-cap: "Reflective Model: causal assumptions. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]
\node [rectangle, draw=black] (L) at (0, 0) {L};
\node [rectangle, draw=white] (eta) at (2, 0) {$\eta$};
\node [rectangle, draw=white] (X1) at (4, 1) {X1};
\node [rectangle, draw=white] (X2) at (4, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (4, -1) {X$_n$};
\node [rectangle, draw=white] (A) at (6, 0) {A};

\node [rectangle, draw=white] (Y) at (8, 0) {Y};

\draw [-latex, bend right=80, draw=black] (L) to (Y);
\draw [-latex, draw=black] (L) to (eta);
\draw [-latex, bend left=90, draw=red] (eta) to (Y);
\draw [-latex, draw=black] (eta) to (X1);
\draw [-latex, draw=black] (eta) to (X2);
\draw [-latex, draw=black] (eta) to (Xn);

\draw [-latex, draw=black] (X1) to (A);
\draw [-latex, draw=black] (X2) to (A);
\draw [-latex, draw=black] (Xn) to (A);

\end{tikzpicture}
```

```{tikz}
#| label: fig-dag-reflective-assumptions_note
#| fig-cap: "Formative model: causal assumptions. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]


\node [draw=black] (L) at (0, 0) {L};
\node [rectangle, draw=black] (X1) at (3, 1) {X1};
\node [rectangle, draw=white] (X2) at (3, 0) {$\vdots$};
\node [rectangle, draw=black] (Xn) at (3, -1) {X$_n$};
\node [rectangle, draw=white] (eta) at (6, 0) {$\eta$};
\node [rectangle, draw=white] (Y) at (9, 0) {Y};



\draw [-latex, draw=black] (X1) to (eta);
\draw [-latex, draw=black] (X2) to (eta);
\draw [-latex, draw=black] (Xn) to (eta);
\draw [-latex, bend right=80, draw=black] (L) to (Y);
\draw [-latex, draw=black, bend left = 80] (L) to (eta);
\draw [-latex, draw=red] (eta) to (Y);


\end{tikzpicture}
```

The reflective model implies $X_i = \lambda_i \eta + \varepsilon_i$, which factor analysts take to imply @fig-structural-assumptions-reflective-model.

The formative model implies $\eta = \sum_i\lambda_i X_i + \varepsilon$, which factor analysts take to imply @fig-dag-reflective-assumptions_note.

## Problems with the structural interpretations of the reflective and formative factor models.

While the statistical model $X_i = \lambda_i \eta + \varepsilon_i$ aligns with @fig-structural-assumptions-reflective-model, it also alings with @fig-dag-formative-assumptions-compatible. Cross-sectional data, unfortunately, do not provide enough information to discern between these different structural interpretations.

Similarly, the statistical model $\eta = \sum_i\lambda_i X_i + \varepsilon$ agrees with @fig-dag-reflective-assumptions_note but it also agrees with @fig-dag-reflectiveassumptions-compatible_again. Here too, cross-sectional data cannot decide between these two potential structural interpretations.

There are other, compatible structural interprestations as well. The formative and reflective conceptions of factor analysis are compatible with indicators having causal effects as shown in @fig_dag_multivariate_reality_again. They are also compatible with a multivariate reality giving rise to multiple indicators as shown in @fig-dag-multivariate-reality-bulbulia.

```{tikz}
#| label: fig-dag-formative-assumptions-compatible
#| fig-cap: "Formative model is compatible with indicators causing outcome.Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false


\begin{tikzpicture}[{every node/.append style}=draw]
%\node [rectangle, draw=white] (L) at (0, 0) {L};
\node [rectangle, draw=white] (eta) at (2, 0) {$\eta$};
\node [rectangle, draw=white] (X1) at (4, 1) {X1};
\node [rectangle, draw=white] (X2) at (4, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (4, -1) {X$_n$};
\node [rectangle, draw=white] (Y) at (6, 0) {Y};

%\draw [-latex, bend right=80, draw=black] (L) to (Y);
%\draw [-latex, bend left=60, draw=black] (L) to (X1);
%\draw [-latex, bend left=40, draw=black] (L) to (X2);
%\draw [-latex, bend right=60, draw=black] (L) to (Xn);

\draw [-latex, draw=black] (eta) to (X1);
\draw [-latex, draw=black] (eta) to (X2);
\draw [-latex, draw=black] (eta) to (Xn);

\draw [-latex, draw=red] (X1) to (Y);
\draw [-latex, draw=red] (X2) to (Y);
\draw [-latex, draw=red] (Xn) to (Y);


\end{tikzpicture}
```

```{tikz}
#| label: fig-dag-reflectiveassumptions-compatible_again
#| fig-cap: "Reflective model is compatible with indicators causing the outcome. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]


%\node [draw=white] (L) at (0, 0) {L};
\node [rectangle, draw=white] (X1) at (2, 1) {X1};
\node [rectangle, draw=white] (X2) at (2, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (2, -1) {X$_n$};
\node [rectangle, draw=white] (eta) at (4, 0) {$\eta$};
\node [rectangle, draw=white] (Y) at (6, 0) {Y};



\draw [-latex, draw=black] (X1) to (eta);
\draw [-latex, draw=black] (X2) to (eta);
\draw [-latex, draw=black] (Xn) to (eta);
%\draw [-latex, bend left=80, draw=black] (L) to (Y);
\draw [-latex, bend left=60, draw=red] (X1) to (Y);
\draw [-latex, bend left=40, draw=red] (X2) to (Y);
\draw [-latex, bend right =60,  draw=red] (Xn) to (Y);



\end{tikzpicture}
```

```{tikz}
#| label: fig_dag_multivariate_reality_again
#| fig-cap: "Multivariate reality gives rise to the indicators, from which we draw our measures. Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]


\node [draw=white] (eta1) at (0, 1) {$\eta_1$};
\node [rectangle, draw=white] (eta2) at (0, 0) {$\vdots$};
\node [rectangle, draw=white] (etan) at (0, -1) {$\eta_n$};
\node [rectangle, draw=white] (X1) at (2, 1) {X$_1$};
\node [rectangle, draw=white] (X2) at (2, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (2, -1 ) {X$_n$};
\node [rectangle, draw=white] (A) at (4, 0 ) {A};
\node [rectangle, draw=white] (Y) at (6, 0 ) {Y};



\draw [-latex, draw=black] (eta1) to (X1);
\draw [-latex, draw=black] (eta2) to (X2);
\draw [-latex, draw=black] (etan) to (Xn);

\draw [-latex, draw=black] (X1) to (A);
\draw [-latex, draw=black] (X2) to (A);
\draw [-latex, draw=black] (Xn) to (A);
\draw [-latex, bend left=80, draw=red] (eta1) to (Y);
\draw [-latex, bend right=80, draw=red] (etan) to (Y);



\end{tikzpicture}
```

```{tikz}
#| label: fig-dag-multivariate-reality-bulbulia
#| fig-cap: "Although we take our constructs, A, to be functions of indicators, X, such that, perhaps only one or several of the indicators are efficacious.Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]


\node [draw=white] (eta1) at (0, 1) {$\eta_1$};
\node [rectangle, draw=white] (eta2) at (0, 0) {$\vdots$};
\node [rectangle, draw=white] (etan) at (0, -1) {$\eta_n$};
\node [rectangle, draw=white] (X1) at (2, 1) {X$_1$};
\node [rectangle, draw=white] (X2) at (2, 0) {$\vdots$};
\node [rectangle, draw=white] (Xn) at (2, -1 ) {X$_n$};
\node [rectangle, draw=white] (Y) at (6, 0 ) {Y};



\draw [-latex, draw=black] (eta1) to (X1);
\draw [-latex, draw=black] (eta2) to (X2);
\draw [-latex, draw=black] (etan) to (Xn);


\draw [-latex, bend left=80, draw=red] (eta1) to (Y);



\end{tikzpicture}
```

VanderWeele's key observation is this:

**While cross-sectional data can provide insights into the relationships between variables, they cannot conclusively determine the causal direction of these relationships.**

This results is worrying. The structural assumptions of factor analysis underpin nearly all psychological research. If the cross-sectional data used to derive factor structures cannot decide whether the structural interpretations of factor models are accurate, where does that leave us?

More worrying still, VanderWeele discusses several longitudinal tests for structural interpretations of univariate latent variables that do not pass.

Where does that leave us? In psychology we have heard about a replication crisis. We might describe the reliance on factor models as an aspect of a much larger, and more worrying "causal crisis"

## VanderWeele's model of reality

VanderWeele's article concludes as follows:

> A preliminary outline of a more adequate approach to the construction and use of psychosocial measures might thus be summarized by the following propositions, that I have argued for in this article: (1) Traditional univariate reflective and formative models do not adequately capture the relations between the underlying causally relevant phenomena and our indicators and measures. (2) The causally relevant constituents of reality related to our constructs are almost always multidimensional, giving rise both to our indicators from which we construct measures, and also to our language and concepts, from which we can more precisely define constructs. (3) In measure construction, we ought to always specify a definition of the underlying construct, from which items are derived, and by which analytic relations of the items to the definition are made clear. (4) The presumption of a structural univariate reflective model impairs measure construction, evaluation, and use. (5) If a structural interpretation of a univariate reflective factor model is being proposed this should be formally tested, not presumed; factor analysis is not sufficient for assessing the relevant evidence. (6) Even when the causally relevant constituents of reality are multidimensional, and a univariate measure is used, we can still interpret associations with outcomes using theory for multiple versions of treatment, though the interpretation is obscured when we do not have a clear sense of what the causally relevant constituents are. (7) When data permit, examining associations item-by-item, or with conceptually related item sets, may give insight into the various facets of the construct.

> A new integrated theory of measurement for psychosocial constructs is needed in light of these points -- one that better respects the relations between our constructs, items, indicators, measures, and the underlying causally relevant phenomena. (VanderWeele 2022)

```{tikz}
#| label: fig-dag-multivariate-reality-complete
#| fig-cap: "Multivariate reality gives rise to the latent variables.Figure adapted from VanderWeele: doi: 10.1097/EDE.0000000000001434"
#| out-width: 100%
#| echo: false

\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{arrows}
\usetikzlibrary{decorations}
\tikzstyle{Arrow} = [->, thin, preaction = {decorate}]
\tikzset{>=latex}

\begin{tikzpicture}[{every node/.append style}=draw]


\node [rectangle, draw=white] (R) at (0, 0 ) {$\mathcal{R}$};
\node [rectangle, draw=white] (c) at (2, -1 ) {concepts};
\node [rectangle, draw=white] (cs) at (4, -2 ) {constructs};
\node [rectangle, draw=white] (eta) at (4, 0 ) {$\eta$};
\node [rectangle, draw=white] (X) at (6, 0 ) {(X$_1 \dots$X$_n$)};
\node [rectangle, draw=white] (A) at (8, 0 ) {A};
\node [rectangle, draw=white] (Y) at (10, 0 ) {Y};



\draw [-latex, draw=black, dashed] (R) to (c);
\draw [-latex, draw=black, dashed] (c) to (cs);
\draw [-latex, draw=black] (R) to (eta);
\draw [-latex, draw=black] (eta) to (X);
\draw [-latex, draw=black] (X) to (A);



\draw [-latex, bend left=80, draw=red] (eta) to (Y);


\end{tikzpicture}
```

This seems to me sensible. However, @fig-dag-multivariate-reality-complete this is not a causal graph. The arrows to not clearly represent causal relations. It leaves me unclear about what to practically do. My thoughts on measurement presented in the main article offer my best attempt to think of psychometric theory in light of causal inference.

## References
